"use strict";

const { contract: textContract } = require("../../meng_v6/text");

const chapter = textContract.chapters.find((item) => item.chapter_id === "C4");
const lineMap = Object.fromEntries(textContract.lines.map((item) => [item.line_id, item.text]));
const CHAPTER_TEXT = chapter.line_ids.map((lineId) => lineMap[lineId]);

function page(value) {
  const required = [
    "page_id", "title", "minutes", "source_line_refs", "original_text",
    "literary_object", "current_difficulty", "unique_function", "visible",
    "first_glance", "information_state", "student_action", "artifact",
    "normal_path", "bounded_feedback", "revision", "teacher_synthesis",
    "story_return", "next_use", "deletion_loss", "merge_test", "visual_duty",
    "interaction_signature", "first_person_reception", "screen", "script",
  ];
  for (const key of required) {
    if (value[key] === undefined || value[key] === null || value[key] === "") {
      throw new Error(`${value.page_id || "unknown"} missing ${key}`);
    }
  }
  if (!Array.isArray(value.student_action) || value.student_action.length < 1 || value.student_action.length > 3) {
    throw new Error(`${value.page_id} student_action must contain 1-3 actions`);
  }
  for (const key of ["teacher_spoken", "scene", "stage_directions", "timeboxes", "branches", "listener_task", "evidence_location", "cut_line"]) {
    if (!value.script[key] || !value.script[key].length) throw new Error(`${value.page_id} script missing ${key}`);
  }
  return value;
}

const pages = [
  page({
    page_id: "C401",
    title: "第四章｜桑叶落下以后，诗写了哪些生活？",
    minutes: 4,
    source_line_refs: chapter.line_ids,
    original_text: CHAPTER_TEXT.join("。") + "。",
    literary_object: "第四章完整声音，以及叙述由桑叶、食贫和淇水经历转入明确责任判断的界面",
    current_difficulty: "学生带着第三章的桑叶假设与脱身问号进入，容易直接寻找婚姻结论，看不见本章先陈述多年经历、随后才辨明责任",
    unique_function: "让第四章完整响起，由学生先标出桑叶的新状态和第一处像在作判断的原句，建立事实在前、判断在后的章内边界",
    visible: `第四章｜桑叶落下以后，诗写了哪些生活？\n\n${CHAPTER_TEXT.map((line) => `${line}。`).join("\n")}\n\n完整读完，再留下：\n桑叶的新样子｜一句你听来像在判断的话`,
    first_glance: "整章原诗占据主位，两个读后入口只定位状态和声音，不提前出现变心、责任或唯一桑叶象征",
    information_state: {
      known: "第三章桑叶为沃若，两项解释仍待筛选；脱身不等的原因尚待婚后事实",
      reveal_now: "第四章完整事件范围、桑叶状态变化和叙述转向判断的初步位置",
      defer: "桑叶解释的修订、食贫与淇水细节、责任判断和男子反复的准确语言",
    },
    student_action: ["完整朗读第四章，读完才抄一处桑叶新状态", "再标出第一处不像讲事情、而像在判断的原句；不确定可留问号"],
    artifact: "04D C401区的桑叶新状态、判断转折原句和一处诚实问号",
    normal_path: "没有听出声音转硬者只写桑叶新状态，判断栏留问号；把食贫当判断者也先保留，后页借词句再修",
    bounded_feedback: "同桌只核对所写是否是第四章原词原句，不解释原因、不宣布责任答案",
    revision: "学生把抽象标签改回原句，或在同桌核对后移动一次判断起点；仍有分歧可保留到C404",
    teacher_synthesis: "只确认桑叶由沃若变为黄而陨，前三句在叙经历，后两句声音转为判断；判断内容留给逐句细读",
    story_return: "迁嫁后的回望继续向前：桑叶落下，多年贫苦和淇水画面出现，随后女子开始直接辨明这段关系",
    next_use: "C402重开桑叶假设，C403读取经历区，C404读取判断起点，C406取回两项初稿重建全章",
    deletion_loss: "若没有整章初读，后页会从教师指定的意象、事实和责任切开讲，学生无法亲自发现声音怎样由经历转入判断",
    merge_test: "不能并入C402：本页必须在解释和对照支架出现前让整章未知声音先发生，C402才用第三章旧稿与新句进行修订",
    visual_duty: "让第四章全文成为唯一主视觉，并以两个读后入口保存学生对状态与判断转折的初次察觉",
    interaction_signature: { cognitive_action: "整体接收与叙述界面察觉", sensory_channel: "完整朗读、原句摘录", social_structure: "个人初读—同桌来源核对", artifact_form: "状态与判断初稿", emotional_rhythm: "画面转冷、声音渐硬" },
    first_person_reception: "我先完整读完第四章，自己找到桑叶的新状态，也试着指出声音从哪一句开始不再只是叙事。",
    screen: { kind: "full", prompt: "桑叶的新样子｜一句你听来像在判断的话", accent_line: 0 },
    script: {
      teacher_spoken: "第三章最后，我们留下两件还不能封口的东西：一张‘沃若’桑叶的双假设卡，一个‘为什么女子更难脱身’的问号。请先把它们放在手边，不急着打开答案。现在让第四章五句诗完整地响一遍。第一遍只听它写了哪些生活；第二遍再留意，女子是否一直都在讲事情，还是有一句开始说她对这段关系的看法。（教师范读，学生再完整低声读。）现在才落笔：桑叶有了什么新样子？抄下原词。再抄一句你听来不像只在讲事情、而像在判断的话。暂时听不出来，就把问号留在这里。同桌只核对是不是第四章里的原词原句，不替对方解释。（等待核对和修订。）我们先把大家找到的句子留在纸上，不急着裁定。接下来从那片桑叶重新读起，让这五句自己告诉我们，她经历了什么，又怎样说起两个人。",
      scene: "屏幕只呈现第四章全文和两个读后入口；教师范读时站到侧面，学生落笔前不染色、不画分区。",
      stage_directions: ["取回第三章桑叶卡和待证问号", "教师完整范读", "学生个人完整低声读", "读后才写状态与判断初稿", "同桌只核对原句来源", "学生亲自修订"],
      timeboxes: [{ label: "恢复第三章两份待证材料", seconds: 30 }, { label: "教师范读和学生完整朗读", seconds: 85 }, { label: "个人生成两项初稿", seconds: 55 }, { label: "同桌来源核对和修订", seconds: 40 }, { label: "引用现场原句并转场", seconds: 30 }],
      branches: [{ kind: "只写悲伤或变心", response: "把抽象词收回，先抄桑叶新状态和你认为声音变硬的完整原句。" }, { kind: "判断起点不同", response: "允许暂存两个位置，不由教师投票裁决；C404比较‘不爽/贰’时再修。" }, { kind: "直接归因女子沉溺", response: "先停止因果判断，本页只登记经历与判断的先后，不把第三章的耽变成伤害责任。" }],
      listener_task: "只检查同伴是否抄自第四章、是否写成原词原句，不评判解释深浅。",
      evidence_location: "04D C401区",
      cut_line: "先回到那片桑叶。第三章它‘沃若’，这一章却‘黄而陨’；你原来的两种想法，经得住这一落吗？",
    },
  }),
  page({
    page_id: "C402",
    title: "沃若｜黄而陨：原来的想法，经得住这一落吗？",
    minutes: 6,
    source_line_refs: ["L011", "L016"],
    original_text: `${lineMap.L011}。${lineMap.L016}。`,
    literary_object: "‘桑之未落，其叶沃若’与‘桑之落矣，其黄而陨’的状态、色彩、位置对照，以及第三章个人意象假设的真实修订",
    current_difficulty: "学生容易把桑叶背成单一象征答案，也可能在新句出现后另写一份解释，却没有真正回看和修改自己先前的理解",
    unique_function: "把第三章两项桑叶假设重新打开，用未落/落、沃若/黄而陨和章内位置决定保留、改写或撤回，让意象意义由前后语境筛选",
    visible: `${lineMap.L011}。\n${lineMap.L016}。\n\n未落／落　沃若／黄而陨\n\n翻回你原来的两种想法：\n保留、改写，还是撤回？为什么？`,
    first_glance: "两句原诗正面对读，屏幕不出现青春、容貌、爱情或关系状态的标准配对；修订权归学生",
    information_state: {
      known: "C302已有两项由沃若感官经验生出的开放假设",
      reveal_now: "陨的词义、两组状态对照、两句章内位置和学生对旧解释的修订",
      defer: "允许青春、情感和关系等解释竞争，不封为唯一答案；全文总结才收纳比兴与结构作用",
    },
    student_action: ["把两句按相同节拍对读，圈未落/落和沃若/黄而陨", "翻回旧假设，对每一项作保留、改写或撤回，并补一处新句或位置依据"],
    artifact: "03C旧桑叶卡上的双色修订痕迹，以及04D C402区的一句当前解释和证据",
    normal_path: "原来留问号者可以现在生成一项；两项都能保留者须说明它们解释的层次不同；没有改变者补写新句如何加强而非假装修改",
    bounded_feedback: "同桌只问新句改变或加强了哪一处，不选择唯一象征义；教师只校准判断强度和语境依据",
    revision: "学生在旧稿上亲自保留、改写或划去，并把‘就是’降为‘可以让人联想到’，写清前后句与位置证据",
    teacher_synthesis: "桑叶荣枯可联想到青春、情感盛衰或关系状态，前后对照同时标志叙事由婚前走向婚后；解释开放但必须受语境约束",
    story_return: "女子回望时，同一棵桑由润泽到枯黄坠落；景物的变化把记忆从感情盛时带向婚后困顿",
    next_use: "C406用修订后的桑叶解释说明本章开头为何转冷；全文知识检索再把这组原句归入比兴、对照和结构转折",
    deletion_loss: "若不重新打开旧稿，意象教学仍是教师公布答案，学生不会体验后文如何迫使解释改变，也没有真实的阅读修订证据",
    merge_test: "不能并入C403：本页注意力必须停在同一物象的前后变化和旧稿修订，C403才转入多年生活与淇水画面",
    visual_duty: "让两句原诗以对等构图显示荣枯变化，并把页面出口指向学生自己的旧稿而非教师答案",
    interaction_signature: { cognitive_action: "前后对照与旧解修订", sensory_channel: "对读、圈词、双色改稿", social_structure: "个人修订—同桌依据追问", artifact_form: "被后文改写的桑叶假设", emotional_rhythm: "鲜润与枯黄在同一眼前相撞" },
    first_person_reception: "我不是再抄一个桑叶答案，而是用第四章的新句回去修改第三章的旧想法，并能说明为什么保留或撤回。",
    screen: { kind: "compare", left_label: "未落", left_lines: [lineMap.L011 + "。"], right_label: "落", right_lines: [lineMap.L016 + "。"], gloss: "陨：坠落", prompt: "翻回原来的两种想法：保留、改写，还是撤回？" },
    script: {
      teacher_spoken: "请把第三章的桑叶卡真正翻回来，不要另起一张新纸。左边读‘桑之未落，其叶沃若’，右边读‘桑之落矣，其黄而陨’。‘陨’是坠落。两句用同样的节拍各读两遍，圈出相互顶住的词：未落与落，沃若与黄而陨。（等待对读。）现在看你原来的两种可能。第四章来了以后，每一种是保留、改写，还是撤回？请直接在旧稿上动笔，旁边补第四章的一处原词，或者补一句位置说明：前一句在迁嫁后的劝告开端，后一句在婚后回顾开端。（等待个人修订。）同桌只追问：新句究竟改变了你哪一处？若没有改变，也要说它怎样加强了你的解释。不同答案可以并存，但‘桑叶就是……’这样一锤定音的话要放轻。我们此刻可以说，桑叶荣枯让人联想到青春、情感或关系状态的变化，也把叙事从婚前带到婚后；究竟偏重哪一层，要让全文语境托住。",
      scene: "屏幕左右只放两句和最低词义；学生桌面必须打开第三章原卡，用另一颜色在原稿上修订，教师不投影成品解释。",
      stage_directions: ["打开第三章旧桑叶卡", "两句同节拍对读", "圈两组状态词", "学生在旧稿上双色修订", "同桌只追问新句造成的改变", "学生补证或降低判断强度"],
      timeboxes: [{ label: "恢复旧稿与两句对读", seconds: 65 }, { label: "圈状态词并校准陨", seconds: 55 }, { label: "个人保留改写撤回", seconds: 100 }, { label: "同桌追问语境依据", seconds: 65 }, { label: "学生再修与教师后置归纳", seconds: 75 }],
      branches: [{ kind: "只等标准答案", response: "请先比较自己两项旧稿受到新句怎样影响；教师不替你选青春、爱情或关系中的一个。" }, { kind: "两项完全一样", response: "把第二项改到不同层次，或诚实撤回，只保留一项有前后句支撑的解释。" }, { kind: "没有修改", response: "允许保留，但必须补写黄而陨怎样加强或限制旧解释，不为形式制造改动。" }],
      listener_task: "只追问新句与章内位置怎样影响旧解，不投票选唯一象征义。",
      evidence_location: "03C旧桑叶卡双色修订＋04D C402区",
      cut_line: "桑叶由盛转衰，诗也从劝告走进日子。接下来的两句，一句压着多年，一句忽然把淇水推到眼前。",
    },
  }),
  page({
    page_id: "C403",
    title: "三岁食贫｜淇水汤汤",
    minutes: 7,
    source_line_refs: ["L017", "L018"],
    original_text: `${lineMap.L017}。${lineMap.L018}。`,
    literary_object: "‘三岁食贫’压缩的长期生活与‘淇水汤汤，渐车帷裳’展开的瞬间画面，以及两种时间尺度共同构成的婚后经历",
    current_difficulty: "学生会把两句平直翻译，却不易感到‘多年’如何被四字压住，也容易为淇水场景擅自补写方向、离开或具体苦难",
    unique_function: "用长音与水声的全班分部朗读体验两种时间尺度，再让每人写一段只含原诗事实的双镜头旁白",
    visible: `${lineMap.L017}。\n${lineMap.L018}。\n\n徂：往　食贫：过贫苦生活\n汤汤：水势浩大　渐：浸湿\n\n一句把多年压在里面；一句让哪一刻忽然展开？`,
    first_glance: "两句和必要词义为主，问题引向时间感；不画定向渡河图，也不提前写‘被休回家’或实际离开",
    information_state: {
      known: "桑叶前后变化已把叙述推入婚后回顾",
      reveal_now: "徂、食贫、汤汤、渐、帷裳的词义；多年压缩与瞬间画面展开的叙述差异",
      defer: "淇水方向和具体时点未明写；责任判断从下一句开始",
    },
    student_action: ["半班拉长‘三岁’，半班让‘汤汤’起伏，交换朗读后写下两种时间感", "用两句第三人称旁白只说多年食贫与水浸车帷，并圈掉一个无原文依据的补写词"],
    artifact: "04D C403区的两种时间感、双镜头旁白和一次想象边界修订",
    normal_path: "不愿做声音变化者按准确字音平读，也要作为听者写出两句时间尺度；没有越界词者不制造错误，只标明事实边界",
    bounded_feedback: "听者只说哪一句更像漫长、哪一句更像眼前一刻；同桌只圈诗中找不到依据的方向、动机或结局词",
    revision: "学生调整一次朗读重音，或删除旁白中的离开、归家、抛弃等提前补写，保留可由原句证明的经历",
    teacher_synthesis: "三岁是多年，食贫是贫苦生活；汤汤写水势浩大，渐是浸湿。诗将长期困顿和一次鲜明水景并置，但不交代渡河方向",
    story_return: "女子把多年贫苦压进‘三岁食贫’，又让淇水浸湿车帷的一刻突然展开；婚后的艰难既漫长，又有触手可及的画面",
    next_use: "C404在这些经历事实之后进入责任判断；全文第二问把多年压力和生活场景转述为现实处境",
    deletion_loss: "删除会让食贫与淇水只剩词义条目，学生既感受不到时间压缩，也容易把未写明的渡河方向和离开情节当成事实",
    merge_test: "不能并入C404：本页必须让经历事实充分成立并守住想象边界，下一页才有资格讨论谁的行为应当被判断",
    visual_duty: "用左右两种尺度呈现被压缩的多年和被展开的水景，让原句而非插图承担时间体验",
    interaction_signature: { cognitive_action: "时间尺度体验与事实边界", sensory_channel: "分部朗读、闭眼听、第三人称写作", social_structure: "全班分部—个人旁白—同桌越界核查", artifact_form: "双镜头事实旁白", emotional_rhythm: "漫长压抑与水势骤近" },
    first_person_reception: "我从声音里感到多年被压缩、一个水景被展开；我能把两句讲成生活片段，也知道诗没有写明渡河方向和结局。",
    screen: { kind: "split", left_label: "多年", left_lines: [lineMap.L017 + "。"], right_label: "一刻", right_lines: [lineMap.L018 + "。"], gloss: "徂：往｜食贫：过贫苦生活｜汤汤 shāng shāng：水势浩大｜渐 jiān：浸湿", prompt: "一句把多年压在里面；一句让哪一刻忽然展开？" },
    script: {
      teacher_spoken: "先把两句说准。‘徂’是往，‘食贫’是过贫苦生活；‘汤汤’读shāng shāng，写水势浩大；‘渐’读jiān，是浸湿；帷裳是车旁的帷幔。现在不急着分析。左半教室读第一句，把‘三岁’读得能让人感到日子很长；右半教室读第二句，让‘汤汤’有水势，但不要喊。交换一次，其余人闭眼听：哪一句像把多年压在四字里，哪一句把一个瞬间推到眼前？（等待两轮朗读和听者落笔。）请每人写两句第三人称旁白：一句只说多年里发生什么，一句只说淇水这一刻看见什么。写完同桌只圈一个诗中找不到的词，比如离开、归家、被赶走、向东向西；作者自己决定删除或改弱。（等待修订。）我们可以看见长期食贫，也可以看见浩荡淇水浸湿车帷；诗没有告诉我们这次渡水的方向，更没有在这里写完她是否离开。事实站稳以后，下一句才开始辨明责任。",
      scene: "屏幕左右显示多年与一刻两句；两半教室交替朗读，学生写旁白时屏幕仍保留原句和最低词义作为边界。",
      stage_directions: ["个人自然口译", "教师定点校音释义", "左右半班分部朗读", "交换声音角色", "个人写双镜头旁白", "同桌只圈越界词", "作者亲自修订"],
      timeboxes: [{ label: "个人口译和定点释义", seconds: 85 }, { label: "两轮分部朗读与闭眼听", seconds: 90 }, { label: "个人双镜头旁白", seconds: 85 }, { label: "同桌越界词核查", seconds: 55 }, { label: "作者修订、分享与转场", seconds: 105 }],
      branches: [{ kind: "把三岁只算三年", response: "按教材语境校准为多年，不把诗中概数锁成精确年限。" }, { kind: "补写归家离开", response: "圈出无原句依据的方向或结局词，改回淇水、水势和车帷被浸的事实。" }, { kind: "不愿变化朗读", response: "允许准确平读，并承担闭眼听者任务；体验不强制表演。" }],
      listener_task: "听辨长期压缩与瞬间展开；核查旁白是否越过原句补写方向、动机或结局。",
      evidence_location: "04D C403区",
      cut_line: "多年食贫，淇水浸帷，这是她讲出的经历。紧接着，她不再只讲发生了什么，而开始说：谁没有差错，谁的行为变了。",
    },
  }),
  page({
    page_id: "C404",
    title: "女也不爽，士贰其行",
    minutes: 6,
    source_line_refs: ["L019"],
    original_text: `${lineMap.L019}。`,
    literary_object: "‘女/士’‘不爽/贰其行’的正面对举，以及叙述者由生活事实进入责任判断的语言证据",
    current_difficulty: "学生可能笼统说双方感情破裂，或用女子沉溺、付出和未及时离开稀释男子行为前后不一的责任",
    unique_function: "通过人人可写、可被原词质询的责任句，让学生从对称语言准确辨明谁没有差错、谁的行为前后不一",
    visible: `${lineMap.L019}。\n\n爽：差错　贰：不专一、前后不一\n\n只用这一句，说清：\n谁怎样？谁又怎样？`,
    first_glance: "一整句和两项最低词义占据中心，不出现成品责任结论；学生必须先独立写，再接受原词质询",
    information_state: {
      known: "前两句已建立多年食贫与淇水场景，事实叙述在前",
      reveal_now: "爽、贰的准确词义；女/士与不爽/贰其行构成的责任判断",
      defer: "男子反复行为如何进一步概括由C405处理；更广原因在全文第三问综合",
    },
    student_action: ["每人用十二至二十字写一条责任判断，并在下方抄两个支撑原词", "同桌只追问‘哪两个词托住’，作者删去双方都有错、她太投入等无据归因"],
    artifact: "04D C404区的个人责任句、两处原词证据和一次删改痕迹",
    normal_path: "已写准确者不制造修改，只把证据下划线；不同意叙述者判断者可保留意见，但须先准确复述诗中判断",
    bounded_feedback: "同桌只能追问原词，不替作者写结论；教师不扩写男子动机，也不把现代道德标签压回诗句",
    revision: "学生亲自把含混的‘两人感情不好’改为有主语和行为的判断，删除将伤害归因于女子投入的因果词",
    teacher_synthesis: "不爽写女子没有差错，贰其行写男子行为不专一、前后不一；诗在这里明确分配行为责任，而非平均摊分",
    story_return: "讲过婚后困顿后，女子第一次正面说出：自己没有差错，男子的行为却前后不一",
    next_use: "C405继续读男子行为如何被概括为无准则、反复；全文第三问把本页列入造成伤害的直接证据",
    deletion_loss: "没有这页，责任会被模糊成‘婚姻失败’或被错误平均，学生也无法从句法对称看见诗中明确的行为归属",
    merge_test: "不能并入C405：本页先建立一条精确责任判断并接受原词质询，下一页才研究语言如何把一次判断推进为反复模式",
    visual_duty: "把同一句中的两侧主语和判断置于同等可比位置，承载学生从原词生成责任句",
    interaction_signature: { cognitive_action: "责任判断与证据质询", sensory_channel: "独立写、原词下划线、口头质询", social_structure: "全员个人主张—同桌证据席—公开抽样", artifact_form: "有原词支撑的责任句", emotional_rhythm: "叙述收紧、责任被说清" },
    first_person_reception: "我没有只说婚姻不幸，而是用不爽和贰其行写清谁做出了怎样的行为判断，也删掉了诗中没有的归责。",
    screen: { kind: "focus", lines: [lineMap.L019 + "。"], gloss: "爽：差错｜贰：不专一、前后不一", prompt: "只用这一句，说清：谁怎样？谁又怎样？" },
    script: {
      teacher_spoken: "请把这句先一分为二，又要合在一起读：‘女也不爽，士贰其行。’爽是差错；贰在这里是不专一、前后不一。现在每个人独立写十二到二十个字，只用这一句说清谁怎样、谁又怎样。句子下面抄两个真正托住你的原词。（静默等待。）同桌进入‘证据席’，只问一句：哪两个词托住你的判断？不要替对方重写。若句子只是‘两个人感情不好’，请把主语和行为补回来；若出现‘她太沉溺所以他才变’或‘双方都有错’，请回到原句，检查这些因果和平均判断有没有证据。作者自己删改。（等待。）我们听两条修订后的句子。诗在这里说得很清楚：女子没有差错，男子的行为却不专一、前后不一。女子的信任和投入可以解释她为什么更难抽身，却不能分担男子行为变化的责任。",
      scene: "屏幕只放大一整句及两项词义；每人先写，随后同桌用原词质询，教师最后引用学生修订句后归纳。",
      stage_directions: ["个人自然口译", "教师校准爽和贰", "全员独立写责任句", "抄两处原词", "同桌只作证据质询", "作者亲自删改", "公开听两条修订句"],
      timeboxes: [{ label: "口译和词义校准", seconds: 70 }, { label: "个人责任句与原词", seconds: 85 }, { label: "同桌证据质询", seconds: 60 }, { label: "作者修订", seconds: 50 }, { label: "公开抽样和教师后置归纳", seconds: 95 }],
      branches: [{ kind: "平均分责", response: "请先准确复述不爽和贰其行各落在谁身上，再决定是否另作现代评论。" }, { kind: "受伤者归责", response: "删除‘因为她投入所以他才……’的因果，把退出困难与造成伤害分开。" }, { kind: "不同意诗中判断", response: "允许保留个人意见，但先写准叙述者此刻怎样判断，并注明你的异议超出本句。" }],
      listener_task: "只追问主张能否由不爽、贰其行和两侧主语这些原词托住，不提供成品句。",
      evidence_location: "04D C404区",
      cut_line: "这一句已经辨明双方。下一句不再只说一次行为变化，而用‘罔极’和‘二三’把反复无常压进四个字。",
    },
  }),
  page({
    page_id: "C405",
    title: "士也罔极，二三其德",
    minutes: 5,
    source_line_refs: ["L020"],
    original_text: `${lineMap.L020}。`,
    literary_object: "‘罔极’和数词‘二三’的活用意义，以及原句相较直白改写所形成的反复、无定感",
    current_difficulty: "学生会把二三误解为两三件事，或只记‘数词活用’术语，却听不出它怎样把男子反复变化写成一种行为模式",
    unique_function: "借原句与直白改写的替换听读，先读准罔极、二三，再让学生用自己的声音和现代话说明反复无常的力度",
    visible: `${lineMap.L020}。\n\n罔极：没有准则\n二三：反复无常\n\n若改成‘他的行为多次改变’，\n哪一种更让你听见无定与反复？`,
    first_glance: "原句占主位，改写只作听觉对照；屏幕给准确词义但不预写数词活用的作用结论",
    information_state: {
      known: "C404已用不爽/贰其行建立行为责任",
      reveal_now: "罔极和二三的词义、二三由数词转为行为状态，以及原句的声音力度",
      defer: "具体反复行为将与第五章至暴、第六章违誓共同回收",
    },
    student_action: ["先读原句，再听教师读直白改写，写下原句多出的声音感", "把二三译成一个有动作感的现代短语，用原句节奏重读并修订一次"],
    artifact: "04D C405区的替换听感、二三现代短语和一处朗读修订",
    normal_path: "认为改写更清楚者可以保留判断，但仍须说出原句在节奏或反复感上多出什么；暂时听不出可留问号",
    bounded_feedback: "听者只报告二三附近是否听见反复与无定，不评价表演；教师后置命名数词活用",
    revision: "学生把‘两三次’改为反复改变、朝三暮四等更准确短语，或依据听者反馈只改一次重音停顿",
    teacher_synthesis: "罔极是没有准则，二三在这里不是数量，而是反复无常；简短数词被用成动作状态，使前后不一成为持续模式",
    story_return: "女子的判断继续加重：男子并非偶然改变一次，而是行为没有准则，品德一再反复",
    next_use: "C406把本句接回责任判断；第五章C503和第六章C604分别以至暴、违誓检验这种反复模式",
    deletion_loss: "删除会丢失二三的准确活用和语言力度，也会使男子反复被误成一次情绪变化，削弱后文证据链",
    merge_test: "不能并入C404：本页的核心是词语替换和听觉检验，C404的核心是责任主张与证据质询，两种注意活动不能同时完成",
    visual_duty: "放大原句和一条直白改写，以最小对照让学生听见‘二三’的动作与节奏价值",
    interaction_signature: { cognitive_action: "词语替换与语言力度判断", sensory_channel: "原句/改句听读、重音修订", social_structure: "个人听辨—同桌定位反馈", artifact_form: "活用短语与朗读痕迹", emotional_rhythm: "一句判断被反复感继续压重" },
    first_person_reception: "我知道二三不是两三件事，而是反复无常；我还能用替换听读说出原句为什么比直白改写更有无定感。",
    screen: { kind: "focus", lines: [lineMap.L020 + "。"], gloss: "罔极：没有准则｜二三：反复无常", prompt: "若改成‘他的行为多次改变’，哪一种更让你听见无定与反复？" },
    script: {
      teacher_spoken: "先读原句：‘士也罔极，二三其德。’罔极是没有准则。二三如果只按数量理解成两三件事，整句会变窄；这里是反复无常。请听我再读一句直白改写：‘他的行为多次改变。’两句都能传达意思，但哪一种更让你听见无定、反复或咬住不放的感觉？先写自己的听感，不必迎合原句一定更好。（等待。）现在把二三译成一个有动作感的现代短语，再用这个理解重读原句。同桌只说：我是否在二三附近听见了反复？没有听见也如实说。读者只改一次停顿或重音。（等待改读。）最后命名：二三本是数词，这里活用来写反复无常。它把‘贰其行’推进一步——不是偶然变过一次，而是行为没有准则、品德一再反复。",
      scene: "屏幕中心是原句，底部只放一条直白改写作为听觉实验；教师不展示最佳朗读符号。",
      stage_directions: ["准确读原句", "教师读直白改写", "个人写真实听感", "写二三现代短语", "同桌定位二三听感", "读者只改一次并重读", "教师后置命名活用"],
      timeboxes: [{ label: "原句释义和改句听读", seconds: 65 }, { label: "个人听感与现代短语", seconds: 75 }, { label: "同桌定位反馈", seconds: 50 }, { label: "个人改读与抽样", seconds: 55 }, { label: "后置命名、故事回接与转场", seconds: 55 }],
      branches: [{ kind: "解释成两三次", response: "回到罔极与教材注释，把数量改为反复无常的行为状态。" }, { kind: "认为改写更清楚", response: "允许保留，同时补说原句在节奏、压缩或动作感上是否仍有增加。" }, { kind: "夸张表演", response: "收回音量，只在二三附近改一次停顿或重音，让原词而非表情承担力度。" }],
      listener_task: "只定位二三附近是否传出反复和无定，不评价感情是否丰富。",
      evidence_location: "04D C405区",
      cut_line: "桑叶落了，日子写了，责任也说清了。现在撤去这些局部提示，把五句诗重新讲成她婚后回望中的一段话。",
    },
  }),
  page({
    page_id: "C406",
    title: "把第四章讲成一段：桑叶落下以后",
    minutes: 5,
    source_line_refs: chapter.line_ids,
    original_text: CHAPTER_TEXT.join("。") + "。",
    literary_object: "第四章完整原诗及桑叶修订、多年食贫、淇水画面、责任辨明和反复判断的连续推进",
    current_difficulty: "学生可能分别记住桑叶、朗读和责任句，却不能离开局部活动说明本章为何先讲经历再作判断",
    unique_function: "完整重读后撤去诗文与学习单，用自然旁白把景物、经历、责任和反复接成连续章意，并写入六章轨道第四格",
    visible: `把第四章讲成一段：桑叶落下以后\n\n${CHAPTER_TEXT.map((line) => `${line}。`).join("\n")}\n\n桑叶怎样变？\n她过着怎样的日子？\n她最后怎样说两个人？`,
    first_glance: "全文重新占主位，三个问题只限定旁白层次；随后必须熄屏、合书、翻背材料进行真实检索",
    information_state: {
      known: "五句已完成意象修订、经历体验、责任质询和词语替换",
      reveal_now: "撤答后能否把事实在前、判断在后的章内因果链讲完整",
      defer: "长期劳作、粗暴、支持缺失将在第五章继续提供事实；全文三问尚不在此封口",
    },
    student_action: ["完整重读后合书、翻背材料并熄屏，用四十秒讲清桑叶—经历—责任三层", "听者只报一个断点，讲述者返诗定位后合书补说，并写故事轨道第四格"],
    artifact: "第四章四十秒旁白、一次查漏补说、故事轨道第四格和带入第五章的反复行为证据",
    normal_path: "完全空白者先说最确定的一层，再只开教材定位前后；没有遗漏者如实确认完整，不为活动制造问题",
    bounded_feedback: "听者只核对景物变化、婚后经历、责任判断三层是否齐全，不代讲；教师只修事实顺序和责任边界",
    revision: "讲述者定位断点后立即合书补说，用自己的自然话写第四格；桑叶多解可保留，责任归属必须准确",
    teacher_synthesis: "引用两条学生章意，整理共同顺序：桑叶由盛转衰，多年食贫和淇水画面出现，女子随后辨明男子前后不一、反复无常",
    story_return: "女子从枯黄桑叶讲到多年贫苦与淇水，又由经历转为判断：自己无过，男子的行为却前后不一、反复无常",
    next_use: "第五章C501从第四格继续，C503用至暴检验反复模式；全文第一问读取六章轨道，第三问读取责任证据链",
    deletion_loss: "没有撤答重建，前五页仍会散成意象、时间和责任知识片段，不能证明学生获得了连续的第四章故事",
    merge_test: "不能并入C405：C405仍在单句和替换支架下理解二三，本页切换为全支架撤除、章内重建和跨章接续",
    visual_duty: "让整章原诗和三个自然旁白层次收束为一页，随后以熄屏制造真实检索并留下第四格",
    interaction_signature: { cognitive_action: "撤答重建与跨章接续", sensory_channel: "完整重读、熄屏旁白、返诗补说", social_structure: "个人旁白—同桌查漏—教师引用", artifact_form: "自然章意与故事轨道", emotional_rhythm: "冷景、困顿与责任判断汇拢" },
    first_person_reception: "我撤去提示以后，仍能讲清桑叶怎样变、哪些是婚后经历、女子怎样从经历走到责任判断，并把它接进完整故事。",
    screen: { kind: "rebuild", prompts: ["桑叶怎样变？", "她过着怎样的日子？", "她最后怎样说两个人？"], rail: "故事轨道｜第四格" },
    script: {
      teacher_spoken: "第四章五句已经逐句走过。先完整重读一遍，让桑叶的荣枯、多年的长度、淇水的水势和后两句的声音各自落稳。（读完。）现在合上教材，把03C和04D都翻到背面，同桌互看桌面没有原诗，我按B键熄暗屏幕。用四十秒把第四章讲给同桌听，只沿三步往前走：桑叶怎样变；她过着怎样的日子；她最后怎样说自己，又怎样说男子。听者讲完以后只报一个真正断点，没有就说完整。交换。（等待。）讲述者只开教材找到漏掉的一句，立即合书补说。现在只翻回04D，在故事轨道第四格写一句自己的章意。谁愿意读？（引用两条，修事实顺序，不替换学生语言。）第四章从枯黄桑叶走进多年贫苦和淇水，女子再明明白白地说：自己没有差错，男子却前后不一、反复无常。下一章，‘三岁’不再只写食贫，还要写她怎样日复一日地生活。",
      scene: "屏幕先供完整重读，随后合书、翻背全部卡片并熄屏；检索后只短暂开教材定位，最后恢复04D写第四格。",
      stage_directions: ["完整重读第四章", "合书并翻背全部材料", "同桌互查桌面", "按B键熄屏", "双方各讲四十秒", "只开教材定位后合书补说", "写故事轨道第四格"],
      timeboxes: [{ label: "完整重读第四章", seconds: 50 }, { label: "撤去教材材料和投影", seconds: 35 }, { label: "双方四十秒旁白", seconds: 95 }, { label: "听者补缺与返诗补说", seconds: 45 }, { label: "写第四格、分享和转场", seconds: 75 }],
      branches: [{ kind: "只报手法", response: "把比兴、对照、活用改成桑叶、食贫、淇水和谁的行为怎样变化。" }, { kind: "把经历当伤害原因", response: "重新分开：经历说明她承受什么；不爽/贰/二三说明谁应为行为负责。" }, { kind: "听者代讲", response: "只指出断点位置，把回诗和补说权还给原讲述者。" }],
      listener_task: "只核对桑叶变化、婚后经历、责任判断三层是否连成一段，不代讲章意。",
      evidence_location: "04D C406区和故事轨道第四格",
      cut_line: "第四格写下了多年食贫与男子反复。第五章会把‘多年’拆成每天，又让粗暴、讥笑和独自悲悼进入同一间屋子。",
    },
  }),
];

const materials = [{
  material_id: "CH4-D",
  file_role: "chapter4_progressive_close_reading_and_story_rail",
  first_distribution_event: "C401_AFTER_COMPLETE_READ",
  visible_when_distributed: "C401初稿区；C402要求同时取回第三章旧桑叶卡；其余按栏展开",
  information_boundary: "首次只露C401；不提前出现桑叶成品解释、责任结论、男子反复或第五章事实",
}];

const payload = {
  schema_version: "1.1",
  module_id: "MENG_V63_CHAPTER_4",
  version: "6.3-chapter4-six-event",
  status: "implementation_candidate",
  module: "chapter_4",
  prerequisite_module: "MENG_V63_CHAPTER_3",
  next_module: "MENG_V63_CHAPTER_5",
  total_minutes: pages.reduce((sum, item) => sum + item.minutes, 0),
  chapter_text: CHAPTER_TEXT,
  materials,
  pages,
};

if (require.main === module) process.stdout.write(`${JSON.stringify(payload)}\n`);
module.exports = payload;
