"use strict";

const CHAPTER_TEXT = "乘彼垝垣，以望复关。不见复关，泣涕涟涟。既见复关，载笑载言。尔卜尔筮，体无咎言。以尔车来，以我贿迁。";

function page(data) {
  return {
    answer_state: "student_generated",
    next_use_status: "pass",
    ...data,
  };
}

const pages = [
  page({
    page_id: "N022", event_id: "E_CH2_WHOLE_READ", next_event_id: "E_CH2_SIGHTLINE",
    title: "第二章｜先听见等待怎样起伏", minutes: 3,
    source_line_refs: ["L006", "L007", "L008", "L009", "L010"],
    primary_visual_duty: "全文/章内整读",
    visible: `第二章｜先听见等待怎样起伏\n${CHAPTER_TEXT}\n每遇到一个人物动作，轻点一下；读完依次写下三个最确定的动作。\n带着感受的动作也可以写。`,
    unique_function: "让学生先拥有第二章完整声音和动作脉冲，避免随后只记哭笑或字词",
    student_action: "每人完整朗读，遇动作轻点桌面，读完写三个最确定的动作；带有情绪意味的动作也可保留，同桌只核对先后",
    first_glance_contract: "读完整章；动作处轻点；写三个动作并核对顺序",
    observable_change: "从只知道婚期已定，变为能从完整声音中抓住至少三个依次发生的动作",
    artifact_location: "学习单·第二章动作脉冲",
    listener_task: "同桌只检查三个动作在诗中的先后，不替对方补完整行动链",
    feedback_revision: "只修订诗中先后；望、泣、笑等合题动作不得因兼有情绪意味而被强制替换",
    deletion_loss: "没有整章初读，等待、哭笑、卜筮和迁嫁会再次被拆成互不相干的知识点",
    method_id: "M_ACTION_PULSE_READ",
    next_use_status: "deferred",
    deferred_use: { target_event_id: "E_CH2_RETRIEVAL", expected_use: "N029取回章首三个动作，在七词中圈出它们，再补成完整顺序" },
    teacher_script: "第一章的婚期定在秋天，第二章从等待真正开始。先让这一章完整地响一遍。每读到一个人物动作，就用指尖轻点桌面一下；带着感受的动作也可以写，不必先把动作和感受硬分开。读完后，只写你最确定的三个动作，按先后排好。同桌不报完整答案，只看顺序有没有倒置；有分歧，就一起把手指落回诗句。把这三步留好，章末我们会看它们怎样长成完整的一章。",
  }),
  page({
    page_id: "N023", event_id: "E_CH2_SIGHTLINE", next_event_id: "E_CH2_CONTRAST",
    title: "乘彼垝垣，以望复关", minutes: 4,
    source_line_refs: ["L006"],
    primary_visual_duty: "原文批注",
    visible: "乘彼垝垣，以望复关。\n人物站位：________\n视线方向：________ → ________\n这是目光，还是行走路线？\n先在纸上画，再与同桌核对‘乘’和‘望’。",
    line_glosses: { L006: { "乘": "登上", "垝垣": "残破的墙", "复关": "卫国地名，氓所住的地方；诗中借所居之地代指氓", "以": "来、用来" } },
    natural_paraphrases: { L006: "她登上残破的墙，用来眺望氓所住的复关。" },
    unique_function: "让学生把登高、远望和所望对象组织为空间关系，而不是停在三个注释上",
    student_action: "每人先借注释口译，再画女子立于垝垣上、由此望向复关的视线，标出乘和望",
    first_glance_contract: "口译原句；自己定位人物；画出视线；核对是目光而非行走路线",
    observable_change: "从知道几个词义，变为能用一条不越界的视线说明女子怎样等待",
    artifact_location: "学习单·第二章视线线条",
    listener_task: "检查画的是目光还是人物行走；只问‘望’指向哪里",
    feedback_revision: "若把女子画在墙下或画成已走到复关，作者依据‘乘’‘望’改为由垝垣上指向复关的视线",
    deletion_loss: "只做口译会失去等待的空间距离和登高远望的动作力度",
    method_id: "M_SIGHTLINE_TRACE",
    teacher_script: "先借注释把这句说清：‘乘’是登上，‘垝垣’是残破的墙，‘以’是来、用来；‘复关’是氓所住的地方，诗中也借地名指向他。现在不要画地图，只画一条目光：女子已站在哪里，她由此望向哪里？如果你把人画在墙下，就回到‘乘’；如果画到复关，就回到‘望’。修好以后，由垝垣上向复关轻轻一指，再把原句读到底。",
  }),
  page({
    page_id: "N024", event_id: "E_CH2_CONTRAST", next_event_id: "E_CH2_SCORE_DESIGN",
    title: "不见与既见，两句怎样突然转身", minutes: 5,
    source_line_refs: ["L007", "L008"],
    primary_visual_duty: "文本比较/关系图",
    visible: "不见复关，泣涕涟涟。\n既见复关，载笑载言。\n先各说成一句自然话，再从原句填三组对照：\n视线条件：____ ↕ ____\n人物动作：____ ↕ ____\n语势原词：____ ↕ ____",
    line_glosses: {
      L007: { "泣涕": "哭泣流泪", "涟涟": "泪流不断的样子" },
      L008: { "既": "已经", "载": "助词，加强语气" },
    },
    natural_paraphrases: {
      L007: "看不见复关，她便哭得泪流不断。",
      L008: "已经看见复关，她便又笑又说。",
    },
    contrast_keys: "不见｜既见；泣涕｜笑言；涟涟｜两个‘载’",
    unique_function: "让学生在同一视野中看见视线变化怎样立即带动动作和声音翻转",
    student_action: "每人先口译两句，再上下对齐三组原词；同桌遮住情绪标签，只凭原词讲转折",
    first_glance_contract: "译两句；对齐三组词；用原词说清转折",
    observable_change: "从分别知道哭与笑，变为能用两组对照和两种语势解释骤变",
    artifact_location: "学习单·第二章两句对照",
    listener_task: "遮住‘失落/喜悦’等标签，检查讲述是否仍能由不见、既见、涟涟、载站住",
    feedback_revision: "漏掉触发条件或语势词者换笔补到相应一行，再连读两句",
    deletion_loss: "拆开讲解会丢失本章最关键的不见/既见正面对照和情绪转轴",
    method_id: "M_CONTRAST_COUPLET",
    teacher_script: "这两句必须放在一起读。先各自说成一句自然话，先别报答案。现在只校准四个词：‘泣涕’是哭泣流泪，‘涟涟’是泪流不断；‘既’是已经，两个‘载’是加强语气的助词。屏幕下面三格还是空的：从两句里各找出视线条件、人物动作和语势原词，上下对齐。同桌不报整套答案，只指出哪一格找不到原词。作者换笔修订后，再遮住‘失落、喜悦’这类情绪词，只用原句把转折说清。",
  }),
  page({
    page_id: "N025", event_id: "E_CH2_SCORE_DESIGN", next_event_id: "E_CH2_LISTENER_TEST",
    title: "先把转折写进声音", minutes: 5,
    source_line_refs: ["L007", "L008"],
    primary_visual_duty: "活动界面",
    visible: "先写朗读谱，再开口。\n不见复关，泣涕涟涟。\n既见复关，载笑载言。\n慢下来的一处：____　快起来的一处：____\n各标一处重音或停顿；为其中一处写下原词理由。",
    unique_function: "让学生先把对照理解转成自己的快慢、停顿和重音方案，而非模仿教师标准读法",
    student_action: "每人独立设计双速度朗读谱，为一处标记写原词依据；再轻声试读自检",
    first_glance_contract: "标快慢；标一处重音/停顿；写一条原词理由；轻声试读",
    observable_change: "从能解释文本对照，变为拥有一份可执行且有原词依据的个人朗读方案",
    artifact_location: "学习单·第二章我的朗读谱",
    listener_task: "本页先做个人准备；提前完成者只检查标记是否能由原词解释，不向同伴示范答案",
    feedback_revision: "教师巡视时只追问‘这个快/慢从哪个字来’，无依据者先修改朗读谱",
    deletion_loss: "没有个人设计，下一页盲听只会检验模仿能力，不能检验学生如何把理解变成声音",
    method_id: "M_READING_SCORE_DESIGN",
    teacher_script: "先别急着互读。把刚才看见的转折写进自己的声音：哪一处慢下来，哪一处快起来？再各标一处重音或停顿。至少选一处写明理由，理由必须落在‘不见、既见、涟涟、载’这样的原词上。你可以和别人读得不同，但不能只写‘因为她很伤心’。轻声试一遍，若纸上的标记自己都读不出来，就先改谱。",
  }),
  page({
    page_id: "N026", event_id: "E_CH2_LISTENER_TEST", next_event_id: "E_CH2_DIVINATION",
    title: "让听者闭眼，只凭声音找转轴", minutes: 5,
    source_line_refs: ["L007", "L008"],
    primary_visual_duty: "活动界面",
    visible: "让听者闭眼，只凭声音找转轴。\n读者：按自己的朗读谱读两句。\n听者：在哪个原词附近，声音开始变化？\n读者根据回执只改一处，再读第二遍。\n第二遍：□更清楚　□仍需调整；仍需调整就标‘△待调整’，章末再试。",
    unique_function: "让朗读方案接受真实听觉检验，并通过听者回执发生一次可听见的修订",
    student_action: "甲读乙闭眼写转轴原词，甲据回执改一处再读；交换角色重复",
    first_glance_contract: "读第一遍；听者写转轴；改一处；读第二遍；交换角色",
    observable_change: "从纸面上自认为读出变化，变为听者能够定位转轴且读者完成一次有方向的改读",
    artifact_location: "学习单·第二章听者回执与改读记录",
    listener_task: "只写听见变化的原词和一处没听清的标记，不评价‘有感情/没感情’",
    feedback_revision: "读者从速度、停顿、重音中只改一处；第二遍若仍不清楚，诚实标记‘待调整’，章末重读时再验证",
    deletion_loss: "没有盲听回执，朗读谱是否真正进入声音无法被检验，活动会停在纸面设计",
    method_id: "M_LISTENER_READING_TEST",
    next_use_status: "deferred",
    deferred_use: { target_event_id: "E_CH2_CHAPTER_RETELL", expected_use: "N030整章重读时再次验证仍标有‘待调整’的朗读谱" },
    teacher_script: "现在才交给同桌。听的人先闭上眼，不看对方的朗读谱；读的人按自己的标记连读两句。听者只写：我在哪个原词附近听见声音转了；哪一处纸上也许标了，但耳朵没听见。读者不争辩，只从速度、停顿、重音里改一处，再读第二遍。听者勾选‘更清楚’或‘仍需调整’。若仍需调整，不必假装成功，就在谱旁标一个‘△待调整’，章末完整重读时再试一次。然后交换角色。我们检验的不是表演得像不像，而是文字能不能经由你的声音被别人听见。",
  }),
  page({
    page_id: "N027", event_id: "E_CH2_DIVINATION", next_event_id: "E_CH2_PARALLEL",
    title: "尔卜尔筮，体无咎言", minutes: 5,
    source_line_refs: ["L009"],
    primary_visual_duty: "原文批注",
    visible: "尔卜尔筮，体无咎言。\n卜｜龟板　筮｜蓍草　体｜兆象　无咎言｜没有不祥之语\n先口译，再把两句话分开：\n此次占问告诉了他们什么？它不能替后来什么作保证？",
    line_glosses: { L009: { "卜": "用火烧龟板，根据裂纹推断吉凶祸福", "筮": "用蓍草的茎占卦", "体": "占卜显示的兆象", "咎言": "不祥之语" } },
    natural_paraphrases: { L009: "你用龟板占卜、用蓍草占卦，占卜显示的兆象没有不祥之语；这只说明此次占问没有显示不祥，不能替后来长期相处作保证。" },
    unique_function: "让学生获得足以口译的先秦卜筮支架，同时守住此次占问与长期关系之间的解释边界",
    student_action: "每人先用四个词口译原句，再把‘此次占问能说到哪里／后来相处尚不能知道什么’分开写；同桌查找越界词",
    first_glance_contract: "认四词；口译；写此次结果；写不能保证；删越界词",
    observable_change: "从对卜筮陌生或把无咎等同幸福，变为能准确说明婚前程序及其证据限度",
    artifact_location: "学习单·第二章卜筮小注",
    listener_task: "查找‘一定、保证、证明’是否把此次占问说成后来结果",
    feedback_revision: "学生生成并互查以后，教师才校准为‘此次占问没有显示不祥’，作者删去把结果推到后来相处的越界词",
    deletion_loss: "没有文化支架便无法准确口译；没有边界便会把仪式性确定误讲成婚姻质量保证",
    method_id: "M_MICRO_CULTURE_BOUNDARY",
    teacher_script: "这句需要一小段文化支架。‘卜’是烧灼龟板看裂纹，‘筮’是用蓍草占卦；‘体’是占卜显示的兆象，‘咎言’是不祥之语。先不听完整翻译，请先各写一句自然话；再把两件事分开写：此次占问能说到哪里？后来相处中的什么，原句尚不能告诉我们？（停四十五秒，教师巡视，不报两格答案；再留时间完成边界句。）同桌只圈出‘一定、保证、证明’这类把时间推远的词，作者先自己改。（等待互查与修订。）现在校准：‘无咎言’是此次占问没有显示不祥；它推进了当时的婚前程序，却不能替后来长期相处作保证。请保留前稿，用另一种颜色修订。",
  }),
  page({
    page_id: "N028", event_id: "E_CH2_PARALLEL", next_event_id: "E_CH2_RETRIEVAL",
    title: "以尔车来，以我贿迁", minutes: 4,
    source_line_refs: ["L010"],
    primary_visual_duty: "文本比较/关系图",
    visible: "以尔车来，以我贿迁。\n以尔｜车｜来　　以我｜贿｜迁\n谁来？带来什么？谁迁？带着什么？\n先拆成两人的动作，再合回一句诗。",
    line_glosses: { L010: { "贿": "财物，这里指嫁妆", "迁": "迁往男子家" } },
    natural_paraphrases: { L010: "你用车来接我，我带着嫁妆迁往你家。" },
    unique_function: "让学生借对称句式看清男子来迎与女子携财物迁嫁两项不同而相接的行动",
    student_action: "每人沿以尔/以我拆两栏口译；两人分别读一栏，再合读原句",
    first_glance_contract: "拆两栏；补主体、物件和动作；对读；合读",
    observable_change: "从一句泛泛的成婚结果，变为能看清双方动作和女子生活资源投入",
    artifact_location: "学习单·第二章以尔／以我对称行动",
    listener_task: "检查两栏的主体、车、嫁妆和迁移动作是否错位",
    feedback_revision: "若把嫁妆说成男子财物或漏掉迁嫁方向，作者回到以我/贿/迁换笔修订",
    deletion_loss: "只说‘他们结婚了’会压扁原句的对称结构、双方行动和女子携财物迁嫁的事实",
    method_id: "M_PARALLEL_ACTIONS",
    teacher_script: "最后一句看上去整齐，却不能一口吞成‘他们结婚了’。沿‘以尔’和‘以我’拆开：你用什么来？我带着什么迁？‘贿’在这里是财物，也就是嫁妆；‘迁’是迁往男子家。请一人读左栏，一人读右栏，再一起合回原句。听的人检查：车是谁带来的，嫁妆是谁带着的，谁的生活位置发生了迁移。错一项，就回到‘以尔、以我’换笔。",
  }),
  page({
    page_id: "N029", event_id: "E_CH2_RETRIEVAL", next_event_id: "E_CH2_CHAPTER_RETELL",
    title: "从章首三步补出七个关键节点", minutes: 4,
    source_line_refs: ["L006", "L007", "L008", "L009", "L010"],
    primary_visual_duty: "活动界面",
    answer_state: "open_question",
    visible: "写回章首三个动作；七词中找得到的圈出，没有出现的照样保留。\n七词复位｜乱序：迁　笑言　望　卜筮　泣　既见　不见\n合上书，按诗中先后标1—7；再在你排好的七词中圈出声音突然转向的一处，用一道转折线连住前后两个节点。\n同桌只找断点；翻诗定位，换笔修订。",
    unique_function: "让章首初读捕捉的三步在细读后与七个关键节点连接，并把不见到既见的声音转折定位在行动链中",
    student_action: "写回章首三个动作，七词中出现的圈出、没有出现的照样保留；合书给七词编号，再在自己的排序中找声音转折并用一道线连住前后节点；同桌只指出断点，作者翻诗修订",
    first_glance_contract: "写回章首三步；能对应的圈出；保留其余；给七词编号；在自己的排序中找转折；翻诗修订",
    observable_change: "从初读只抓到三个动作，变为能把自己的初读和七个关键节点连接，并定位全章最清楚的转折",
    artifact_location: "学习单·第二章章首三步与七词复位",
    listener_task: "只说哪一处顺序跳跃，或转折线所连的两个节点是否相邻，不报完整顺序和正确转折词",
    feedback_revision: "作者翻诗只定位断点，换笔调序或移动转折线；章首三步只按原诗先后修订，没有出现在七词中的合理动作照样保留",
    deletion_loss: "没有取回和扩展，章首初读产物无后用，也无法检验细读是否把三步理解长成完整一章",
    method_id: "M_SCRAMBLED_ACTION_VOICE",
    teacher_script: "请先把章首写下的三个动作抄回这一格。再看屏幕七词：找得到的就圈出来；像‘乘、来’这样没有出现在七词里的，照样保留，只要它来自原诗。现在把书合上。七词不是整章全部动作，而是七个关键节点：迁、笑言、望、卜筮、泣、既见、不见。请按诗中的先后标一到七。排完以后，只看你自己的序列：声音在哪两个相邻节点之间突然转了？圈出这一处，再用一道转折线连住前后两个节点。写完交给同桌；听的人只说顺序断点在哪里，或你连住的两项是否相邻，不报完整顺序，也不说正确转折词。作者再翻诗，只定位断点，用另一种颜色修订，然后合书连说一次。看看章首三步，现在怎样和七个关键节点接在一起。",
  }),
  page({
    page_id: "N030", event_id: "E_CH2_CHAPTER_RETELL", next_event_id: "E_CH3_START",
    title: "让第二章从等待走到迁嫁", minutes: 4,
    source_line_refs: ["L006", "L007", "L008", "L009", "L010"],
    primary_visual_duty: "全文/章内整读",
    visible: `第二章全文\n${CHAPTER_TEXT}\n完整重读，再用30秒讲清：她怎样等｜声音怎样转｜婚事怎样推进。`,
    unique_function: "把空间、对照、声音、文化程序和迁嫁重新收束为一段连续的第二章叙事",
    student_action: "每人重读全章，合书作三十秒旁白；听者按三项找遗漏，讲述者回诗补说并写章意",
    first_glance_contract: "读完整章；合书讲30秒；按三项反馈补说；写一句章意",
    observable_change: "从能完成局部活动，变为能连续讲清等待、情绪转折、卜筮与迁嫁的因序",
    artifact_location: "学习单·第二章一句章意；同桌三十秒旁白",
    listener_task: "只检查三项：她怎样等、声音怎样转、婚事怎样推进",
    feedback_revision: "遗漏者回到相应原句定位，补说后写成一句有动作而非主题标签的章意",
    deletion_loss: "没有整章回读和连续旁白，空间线、朗读谱与文化小注仍会散落为三个活动",
    method_id: "M_CHAPTER_RETELL",
    next_use_status: "deferred",
    deferred_use: { target_event_id: "E_Q1_LIFE_RELAY", expected_use: "六章人生接力读取第二章一句章意与至少一处原词" },
    teacher_script: "把第二章重新完整读一遍。若你的朗读谱还标着‘△待调整’，读到‘不见／既见’两句时就按最后一次修改再试；同桌只在旁边勾‘更清楚’或保留‘待调整’，不必假装已经解决。视线线条、两句对照、卜筮小注都退到诗句后面，让这一章重新成为一段话。读完合书，用三十秒讲清三件事：她怎样等，声音怎样转，婚事怎样推进。听的人只按这三项找遗漏；少一项，讲述者回到相应原句补说。最后写一句有动作、有转折的章意。下一章，叙事会忽然转向桑叶。",
  }),
];

const payload = { schema_version: "1.0", chapter_id: "C2", chapter_text: CHAPTER_TEXT, pages };

if (require.main === module) process.stdout.write(`${JSON.stringify(payload)}\n`);

module.exports = payload;
