"use strict";

const CHAPTER_TEXT = "氓之蚩蚩，抱布贸丝。匪来贸丝，来即我谋。送子涉淇，至于顿丘。匪我愆期，子无良媒。将子无怒，秋以为期。";

function page(data) {
  return {
    answer_state: "student_generated",
    primary_visual_duty: "原文批注",
    next_use_status: "pass",
    ...data,
  };
}

const pages = [
  page({
    page_id: "N013", event_id: "E_CH1_WHOLE_READ", next_event_id: "E_CH1_LINE1",
    title: "第一章｜先看两个人怎样行动", minutes: 3,
    primary_visual_duty: "全文/章内整读",
    source_line_refs: ["L001", "L002", "L003", "L004", "L005"],
    visible: `第一章｜先看两个人怎样行动\n${CHAPTER_TEXT}\n圈出男子的动作，划出女子的动作。暂时只追踪“谁做了什么”。`,
    unique_function: "让学生先拥有第一章完整声音和人物行动轮廓，再进入逐句释义",
    student_action: "每人朗读第一章，圈男子动作、划女子动作；同桌逐项核对行动主体",
    first_glance_contract: "读完整章；圈男子动作、划女子动作；核对到章末结束",
    artifact_location: "教材第一章原句旁",
    listener_task: "同桌只问‘这是谁做的’，不先报完整章意",
    feedback_revision: "行动主体标错或漏标者换笔修订，再完整读一遍",
    deletion_loss: "没有整章初看，随后五组诗句会退化为彼此割裂的字词翻译",
    method_id: "M_ACTOR_MARK",
    teacher_script: "四言的句子很短，我们很容易一头扎进字词，却忘了这是两个人正在相遇、说话。先把第一章完整读一遍，不急着判断谁好谁坏。请圈出男子做的动作，划出女子做的动作。读完后和同桌逐项核对，只问一句：这是谁做的？有不同，就把手指落回原句，再换笔改。",
  }),
  page({
    page_id: "N014", event_id: "E_CH1_LINE1", next_event_id: "E_CH1_LINE2",
    title: "氓之蚩蚩，抱布贸丝", minutes: 4,
    source_line_refs: ["L001"], original_text: "氓之蚩蚩，抱布贸丝",
    visible: "氓之蚩蚩，抱布贸丝。\n先看眼前这个出场：谁｜怎样｜拿什么｜做什么\n把四格说成一句自然话；只写眼前，不忙替后来下结论。",
    glosses: { "氓": "民，这里指诗中的男主人公", "蚩蚩": "忠厚的样子", "贸": "交易、交换" },
    natural_paraphrase: "那个男子看起来忠厚，抱着布来换丝。",
    unique_function: "让学生从出场神态和动作获得男子的第一眼形象，同时知道形象只是当下所见",
    student_action: "每人先口译原句，再用三个定点释义校准；换笔修改一处不准表达",
    first_glance_contract: "先填谁、怎样、拿什么、做什么四格；说成自然话；再查三个词并留下修改痕迹",
    artifact_location: "学习单·第一章逐句札记L001",
    listener_task: "核对话中是否同时有男子、样子、布和交换动作",
    feedback_revision: "遗漏主体、神态或动作时，作者依据原词换笔补全并重读",
    deletion_loss: "直接跳过本句会失去第一章初见印象的文本来源",
    method_id: "M_GLOSS_REVISE",
    teacher_script: "先不要看我给出的现代话，借注释自己说：谁，以怎样的样子，拿着什么来做什么？说给同桌听。现在核对三个词：氓，这里是诗中的男主人公；蚩蚩，是忠厚的样子；贸，是交换。请换笔改一处不够准确的说法，再读原句。注意，我们此刻知道的是他出场时看起来怎样，还不是他一生的品格证明。",
  }),
  page({
    page_id: "N015", event_id: "E_CH1_LINE2", next_event_id: "E_CH1_LINE3",
    title: "匪来贸丝，来即我谋", minutes: 5,
    source_line_refs: ["L002"], original_text: "匪来贸丝，来即我谋",
    visible: "匪来贸丝，来即我谋。\n诗句先写的动作：________\n女子随后说明的来意：________\n圈出让意思转过来的字。",
    glosses: { "匪": "不是", "即": "就、靠近", "谋": "谋划、商量，这里指商量婚事" },
    natural_paraphrase: "他不是真来换丝，而是到我这里商量婚事。",
    unique_function: "让学生看见诗句如何从先写的贸丝动作转到女子随后说明的议婚来意，但不把文本次序扩写成完整人格判断",
    student_action: "每人分别写下诗句先写的动作和女子随后说明的来意，并圈‘匪’；同桌检查结论是否只说到诗句能证明的程度",
    first_glance_contract: "写先出现的动作；写随后说明的来意；圈转折字；不评价完整人格",
    artifact_location: "学习单·第一章逐句札记L002",
    listener_task: "只核对‘贸丝、谋婚、匪’是否对应，不替对方贴人物标签",
    feedback_revision: "若把文本先后直接说成有意伪装或欺骗，作者删去越界词，改写为诗中明写的动作和来意",
    deletion_loss: "没有这一步，学生既看不见叙事转折，也容易在全文后无边界倒推",
    method_id: "M_INTENT_CONTRAST",
    teacher_script: "这一句自己把前一句翻了过来。请先写两格：诗句先写了他什么动作；女子随后又说明他此来要商量什么。哪个字让意思转过来？对，是‘匪’。再核对‘即’是走近、到这里，‘谋’在这里是商量婚事。现在用‘不是……而是……’说完整。诗句能证明动作和来意之间有转折；至于他是否有意伪装或欺骗，单凭这一句还不能断言。",
  }),
  page({
    page_id: "N016", event_id: "E_CH1_LINE3", next_event_id: "E_CH1_LINE4",
    title: "送子涉淇，至于顿丘", minutes: 4,
    source_line_refs: ["L003"], original_text: "送子涉淇，至于顿丘",
    visible: "送子涉淇，至于顿丘。\n沿着三个动作画一条线：送 → 涉 → 至。\n是谁在送？送到哪里才停下？",
    glosses: { "涉": "渡过", "淇": "淇水", "顿丘": "地名" },
    natural_paraphrase: "我送你渡过淇水，一直送到顿丘。",
    unique_function: "让学生借空间移动感受女子的主动投入，而非只记两个地名",
    student_action: "每人画出送—涉—至的路线并补人物，随后把三个动作说成一句连续现代话",
    first_glance_contract: "画行动线；标出谁在送；用一句话说到顿丘",
    artifact_location: "学习单·第一章送行路线",
    listener_task: "寻找路线是否漏了渡淇或终点，指出断点而不代画",
    feedback_revision: "作者依据‘送、涉、至’补回断点，再从原句读到终点",
    deletion_loss: "只译地名会失去送行行动的长度和关系投入",
    method_id: "M_ROUTE_TRACE",
    teacher_script: "这句没有直接说‘不舍’，只写了一段路。请沿着三个字画线：送、涉、至。是谁在送？从哪里越过去？最后到了哪里？把人物和终点补上，再说成一句现代话：我送你渡过淇水，一直送到顿丘。现在再读原句，让三个动作一口气走到‘顿丘’，不要把这段路读断。",
  }),
  page({
    page_id: "N017", event_id: "E_CH1_LINE4", next_event_id: "E_CH1_LINE5",
    title: "匪我愆期，子无良媒", minutes: 4,
    source_line_refs: ["L004"], original_text: "匪我愆期，子无良媒",
    visible: "匪我愆期，子无良媒。\n两种读法，哪一种更贴近原句？\n她在拒绝这门婚事？｜她在说明此刻不能成婚的条件？\n先圈一项，再抄下托住判断的原词。",
    glosses: { "愆期": "拖延婚期", "良媒": "合适的媒人" },
    natural_paraphrase: "不是我故意拖延婚期，是你没有合适的媒人。",
    unique_function: "让学生辨认女子既亲近又仍坚持媒妁条件的对话层次",
    student_action: "每人先在两种读法中圈选并抄原词；同桌核对后再借释义修订，并用自然话说清解释和条件",
    first_glance_contract: "先在两种读法中选择；抄原词；同桌核对；教师校准后修订",
    artifact_location: "学习单·第一章逐句札记L004",
    listener_task: "核对是否误说成女子拒绝婚姻，或漏掉媒人条件",
    feedback_revision: "依据‘匪、子无良媒’把说满的‘拒绝/拖延’改成原句能够托住的解释",
    deletion_loss: "没有此句，女子的条件和边界会被简化成单纯顺从或拒绝",
    method_id: "M_CLAUSE_SORT",
    teacher_script: "这里第二次出现‘匪’。先不听我的解释，只看原句，在两种读法里圈出更贴近的一项：她是在拒绝这门婚事，还是在说明此刻不能成婚的条件？再抄下托住判断的原词。（停四十五秒，教师巡视，不报答案。）现在同桌互相看一眼：你的选择由哪个词托住？（等待核对。）我们再校准词义：‘愆期’是拖延婚期，‘良媒’是合适的媒人。请回到刚才的选择，用‘不是……而是……’说成一句自然话；若原先把话说成拒绝或故意拖延，就依据‘匪我愆期，子无良媒’换笔改得更准确。",
  }),
  page({
    page_id: "N018", event_id: "E_CH1_LINE5", next_event_id: "E_CH1_RETRIEVAL",
    title: "将子无怒，秋以为期", minutes: 5,
    source_line_refs: ["L005"], original_text: "将子无怒，秋以为期",
    visible: "将子无怒，秋以为期。\n先借注释，把一句话分成两层：\n她先在劝什么？｜她又把什么定下来？\n校准词义后，标重音和停顿，读给同桌听。",
    glosses: { "将": "愿、请", "无": "同‘毋’，不要", "以……为期": "把……定作婚期" },
    natural_paraphrase: "请你不要生气，我们就把秋天定作婚期。",
    unique_function: "让学生通过释义和朗读听见请求、安抚与明确约期并存",
    student_action: "每人先译句，再标重音和停顿；同桌说出实际听见的语气，读者调整后重读",
    first_glance_contract: "译清请求和婚期；标重音停顿；根据听者反馈重读",
    artifact_location: "学习单·第一章朗读谱L005",
    listener_task: "不用情绪标签打分，只指出听见安抚或约期的原词",
    feedback_revision: "听者若只听见命令或只听见承诺，读者调整‘将、无怒、秋、期’的重音和停顿",
    deletion_loss: "没有声音加工，‘无怒’与婚期承诺会退化成两条孤立翻译",
    method_id: "M_TONE_READING",
    teacher_script: "‘将’在这里读qiāng。先别听我的释义，请借教材注释，把这句话分成两层：她先在劝什么？又把什么定下来？（停四十五秒，教师巡视，不报两层答案。）现在和同桌比较，看看两层话有没有混在一起。（等待核对。）我们再校准：‘将’是愿、请，‘无’同‘毋’，是不要；‘以……为期’是把……定作婚期。请换笔修订，再说成一句自然话。然后标一处重音、一处停顿，读给同桌听。听的人不先贴情绪标签，只说自己从‘将、无怒、秋、期’里实际听见了哪一层。读者根据反馈改读一次。‘无怒’值得以后重看，但此刻不能把它直接说成已经发生了暴力。",
  }),
  page({
    page_id: "N019", event_id: "E_CH1_RETRIEVAL", next_event_id: "E_CH1_FIRST_IMPRESSION",
    title: "合上书，把这场相遇接起来", minutes: 4,
    primary_visual_duty: "活动界面",
    source_line_refs: ["L001", "L002", "L003", "L004", "L005"], answer_state: "open_question",
    visible: "合上书，把这场相遇接起来。\n独立写五步，只写动作，不抄原句。\n同桌只找断点，不报答案；再翻书定位，换笔修订。",
    unique_function: "检验逐句理解能否离开答案页重建为连续事件",
    student_action: "合书独立写五步行动链；同桌指出断点；本人翻书定位后换笔修订",
    first_glance_contract: "合书写五步；听断点；翻书换笔修订",
    artifact_location: "学习单·第一章五步行动链",
    listener_task: "只说‘这里少了一步/主体变了’，不顺口报出完整答案",
    feedback_revision: "作者回诗定位断点，换笔补回或调序，再口头连说一次",
    deletion_loss: "没有撤答检索，逐句讲解是否形成连续理解无法被发现",
    method_id: "M_RETRIEVAL_CHAIN",
    teacher_script: "现在把书轻轻合上，屏幕也不给行动答案。请独立写五步，只写谁做了什么，不抄原句。写完和同桌交换。听的人只找断点：这里是不是突然跳了？这个动作是谁做的？不要顺口把完整答案报出来。作者再翻书定位，用另一种颜色补回或调序。最后合上书，把五步连着说一遍。",
  }),
  page({
    page_id: "N020", event_id: "E_CH1_FIRST_IMPRESSION", next_event_id: "E_CH1_CHAPTER_RETELL",
    title: "只读第一章，你怎样看这次接近？", minutes: 5,
    primary_visual_duty: "活动界面",
    source_line_refs: ["L001", "L002", "L004", "L005"],
    visible: "只读第一章，你怎样看这次接近？\n诗里写着｜初读时我觉得｜现在还说不准\n每栏写一条；给前两栏各补一个原词。全文读完后，我们再回来。",
    unique_function: "保存没有被结局倒灌的初见判断，并建立事实、印象与断言限度",
    student_action: "每人填写三栏并补原词；同桌查找说满之处，作者现场保留、说轻一点或移栏",
    first_glance_contract: "三栏各一条；前两栏各有原词；听质询后修订",
    artifact_location: "学习单·第一章初见档案",
    listener_task: "查一条判断：它是诗中明写、个人印象，还是已经说过了证据",
    feedback_revision: "作者把越界判断移入‘现在还说不准’，或改成较轻的初读印象",
    deletion_loss: "没有初见档案，全文后无法比较判断怎样被新证据改变",
    method_id: "M_EVIDENCE_BOUNDARY",
    artifact_columns: ["诗里写着", "初读时我觉得", "现在还说不准"],
    next_use_status: "deferred",
    deferred_use: { target_event_id: "E_CHAPTER1_RETURN", expected_use: "全文后回看初见档案，逐条保留、改写或撤回" },
    teacher_script: "这一次只站在第一章里，不借用后来结局。请写三栏：诗里写着什么；初读时你觉得怎样；还有什么现在仍说不准。前两栏各补一个原词。同桌挑一条问：这是诗里写着的，还是你此刻的感觉？有没有说得比原词更满？作者可以保留，可以把话说轻一点，也可以移到‘现在还说不准’。把这张初见札记保存好，全文读完后我们再回来。",
  }),
  page({
    page_id: "N021", event_id: "E_CH1_CHAPTER_RETELL", next_event_id: "E_CH2_START",
    title: "让第一章重新成为一段话", minutes: 4,
    primary_visual_duty: "全文/章内整读",
    source_line_refs: ["L001", "L002", "L003", "L004", "L005"],
    visible: `第一章全文\n${CHAPTER_TEXT}\n完整重读。再用30秒讲清：男子怎样来｜女子怎样回应｜婚期怎样定。`,
    unique_function: "把字词、行动、对话和声音重新收束成可连续表达的第一章理解",
    student_action: "每人重读全文，合书作三十秒旁白；听者按三项标准找遗漏，讲述者回诗补说",
    first_glance_contract: "读完整章；合书讲30秒；依据三项反馈补说",
    artifact_location: "学习单·第一章一句章意；同桌口头旁白",
    listener_task: "只检查三项是否齐全：男子怎样来、女子怎样回应、婚期怎样定",
    feedback_revision: "遗漏者回到相应原句定位，补说后再用一句话写章意",
    deletion_loss: "没有整章回读和旁白，局部知识仍未重新回到完整故事与声音",
    method_id: "M_CHAPTER_RETELL",
    retell_criteria: "男子怎样来｜女子怎样回应｜婚期怎样定",
    teacher_script: "把第一章重新打开，完整读一遍。刚才学过的字词不要抢在诗句前面，让两个人的行动和对话连起来。读完合上书，用三十秒讲清三件事：男子怎样来，女子怎样回应，婚期怎样定。听的人只按这三项找遗漏。若少了一项，讲述者回到原句定位，再补说一次，最后把本章写成一句自然话。下一章，约定婚期以后，等待真正开始。",
  }),
];

const payload = { schema_version: "1.0", chapter_id: "C1", chapter_text: CHAPTER_TEXT, pages };

if (require.main === module) process.stdout.write(`${JSON.stringify(payload)}\n`);

module.exports = payload;
