"use strict";

const pages = [
  {
    page_id: "N001", event_id: "E_TITLE", unit_role: "输入", visual: "题名", minutes: 1,
    legacy_ids: ["S002"],
    title: "氓",
    visible: "氓\n《诗经·卫风》",
    function: "作为课堂进入事件的题名载体，只命名共同阅读的作品并聚拢注意，不独自虚构学习变化或后用",
    prerequisite: "学生已翻到课文",
    input: "教材中的《氓》题名和出处",
    action: "看题名、出处并在教材中定位全文",
    artifact: "课堂进入状态",
    listener: "听清题名出处，核对自己翻到的文本",
    change: ["注意尚未聚拢", "共同面向《氓》题名与出处", "学生已翻到相同文本"],
    location: "教材题名旁",
    previous: "课堂开始",
    next: "从旧有文学经验进入爱情与婚姻主题",
    loss: "失去共同文本和审美基调的安静入口",
    framework: "不引入中心思想或结尾情绪",
    next_event_id: "E_QUESTIONS",
  },
  {
    page_id: "N002", event_id: "E_RECALL_PERSONAL", unit_role: "生成", visual: "活动界面", minutes: 2,
    legacy_ids: ["S003", "S004"],
    title: "想起哪些爱情或婚姻故事？",
    visible: "想起哪些爱情或婚姻故事？\n写下1—3篇初高中语文课上读过的课文或整本书。\n每篇只写：篇名＋它写了什么。\n一时想不起：翻教材目录｜领取一张只写篇名的提示条｜先听后补",
    function: "让每名学生先从自己的语文学习经历中广泛检索作品和朴素主题",
    prerequisite: "只需回忆篇名或一个情节，不要求关系分析框架",
    input: "个人初高中语文学习记忆、教材目录和45秒后按需领取的篇名提示条",
    action: "每人独立写下1—3篇作品，并用一句自然话写它讲了什么",
    artifact: "个人作品清单",
    listener: "本阶段静默书写；完成者再补一篇不同类型作品",
    change: ["等待教师列举作品", "每人拥有一份可说的旧经验", "清单含篇名和朴素主题"],
    location: "学习单·旧故事清单",
    previous: "题名之后暂不进入预制结论",
    next: "四人轮说扩展小组公共记忆",
    loss: "没有个人准备，后续小组容易被少数记忆快的学生包办",
    framework: "提示条由教师按本班真实学习进度提前准备，正面只列已经学过的作品篇名，不写主题；开始时扣放在讲台，45秒仍空白者举手领取",
    visual_implementation: "初始屏只显示三行主任务；45秒后页脚淡入三条恢复路径。提示条是纸卡，不另加作品答案页。",
    next_event_id: "E_RECALL_GROUP",
  },
  {
    page_id: "N003", event_id: "E_RECALL_GROUP", unit_role: "交流", visual: "活动界面", minutes: 3,
    legacy_ids: ["S003", "S004"],
    title: "把四个人的故事放在一起",
    visible: "把四个人的故事放在一起\n依次发言：每人15—20秒\n只说：篇名＋它写了什么\n记录者记篇名和主题短语；听的人各勾一项自己未想到的内容\n重复作品，可以补一个不同主题",
    function: "让每名学生的个人旧经验进入小组公共作品谱",
    prerequisite: "每人已有作品清单；空白者可先听一位同伴后补写",
    input: "四份个人作品清单",
    action: "四人依次发言，每人15—20秒，记录者同步记篇名和主题短语",
    artifact: "小组作品谱",
    listener: "其余三人勾记自己未想到的作品或主题，不重复代说",
    change: ["个人清单彼此隔离", "小组形成多人共同作品谱", "记录中可追溯每人贡献"],
    location: "学习单·小组作品谱",
    previous: "调用个人作品清单",
    next: "每组向全班贡献新增作品或不同主题",
    loss: "省略轮说会使全员入口退化为自愿发言",
    framework: "不要求深析，只扩大文学主题的广度",
    next_event_id: "E_RECALL_CLASS",
  },
  {
    page_id: "N004", event_id: "E_RECALL_CLASS", unit_role: "交流", visual: "活动界面", minutes: 4,
    legacy_ids: ["S005"],
    title: "让班级作品谱再大一点",
    visible: "让班级作品谱再大一点\n每组先贴一张卡，再说20秒：\n贡献一篇尚未出现的作品，或补一个不同主题。\n听众：勾下一项自己未想到的内容。\n八组公开与换组：最多4分钟",
    function: "在受控时间内把八组材料扩展为全班可见的爱情与婚姻文学范围",
    prerequisite: "每组已有作品谱，并能识别哪些内容尚未出现",
    input: "各组作品谱和一张写有‘篇名＋它写了什么’的贡献卡",
    action: "每组代表先把贡献卡贴入现场区，再用20秒说新增作品或不同主题；重复时指出一项有依据的联系",
    artifact: "八张可追溯的班级贡献卡和个人新增记录",
    listener: "每人勾下一项自己未想到的作品或主题",
    change: ["只知道本组作品", "看见全班更广的文学主题", "每人留下至少一项新增记录"],
    location: "学习单·我未想到的一项；黑板或磁贴板现场区",
    previous: "调用小组作品谱",
    next: "教师只用现场材料整理主题谱",
    loss: "没有全班扩展，导入仍局限于少数固定篇目",
    framework: "按八组计算：每组20秒表达，另给平均10秒贴卡和换组，共4分钟；更多小组先同主题并组",
    visual_implementation: "屏幕左侧固定20秒倒计时和听众任务，右侧只标示贴卡位置；作品内容留在真实黑板或磁贴板，不用预填动画冒充现场材料。",
    next_event_id: "E_THEME_MAP",
  },
  {
    page_id: "N005", event_id: "E_THEME_MAP", audit_scope: "learning_page", unit_role: "收束", visual: "现场共创", minutes: 4,
    legacy_ids: ["S005"],
    title: "我们读过的爱情与婚姻故事",
    visible: "我们读过的爱情与婚姻故事\n看一看这八张卡：哪些在说相近的事？\n请一位同学移动一张卡，并说说理由。\n教师据此串联；全班核对作品与说法是否相配。",
    function: "把全班实际说出的作品和自然话归类成可追溯主题谱，不预填婚姻处方",
    prerequisite: "班级已经贡献作品和主题短语",
    input: "黑板或磁贴板上的八张‘篇名＋它写了什么’贡献卡",
    action: "先静看卡片；一名学生试移一张相近卡并说明理由；教师只沿现场卡片作两三条串联；全班核对，发现错配即纠正",
    artifact: "班级爱情与婚姻文学主题谱",
    listener: "每人任选一张卡核对篇名与说法；发现错配可直接指出，未发言者在学习单补记一处相近或不同",
    change: ["作品和主题仍零散", "形成带作品出处的宽广主题场", "每个主题至少保留一篇现场作品"],
    location: "黑板或磁贴板主题谱；学习单·相近与不同",
    previous: "只读取现场班级材料",
    next: "圆桌讨论回看主题谱，比较《氓》带来的新认识",
    loss: "没有主题谱，广泛发言不能沉淀为后续可调用的共同记忆",
    framework: "4分钟分配：静看30秒，学生试移与理由40秒，教师依卡串联90秒，全班核对60秒，留20秒拍照或补记；未由学生材料触发的词不上屏",
    visual_implementation: "PPT只保留观察、移动、核对三步；真实贡献卡是主视觉。教师不在PPT预制分类框，不用动画伪造学生答案。",
    next_event_id: "E_MARRIAGE_ROUND_TABLE",
    deferred: { target_batch: "marriage_roundtable", expected_use: "圆桌讨论回看班级主题谱并修订婚姻判断" },
  },
  {
    page_id: "N007", event_id: "E_QUESTIONS", unit_role: "输入", visual: "活动界面", minutes: 1,
    legacy_ids: ["S002", "S006", "S007", "S008", "S009"],
    title: "读完六章，再回答",
    visible: "读完六章，再回答\n一、她经历了什么？\n二、她婚后的不幸，在生活中是什么样子？\n三、这场婚姻为什么走到这一步？",
    function: "建立全文导航，只让学生读三问，不在缺少文本时写高阶猜想",
    prerequisite: "学生已知道《氓》是女子回望婚后日子的叙事",
    input: "三道朴素问题",
    action: "静默读三问，只在问题旁标记最想追踪的一问",
    artifact: "一处问题标记",
    listener: "听教师明确‘现在不回答’，核对自己没有抢写原因",
    change: ["不知道全文阅读方向", "拥有三个朴素追踪问题", "保留一项个人追踪重点"],
    location: "学习单·三问导航",
    previous: "教师用一句自然转场承接现场主题谱：今天再读一个更早的故事；它不只写相遇，还由一位女子回望婚后的日子。转场不上独立页面、不预给结论",
    next: "不中断完整听读六章",
    loss: "没有导航，初听停顿难以在全文后回收到核心问题",
    framework: "不要求初始猜想，不拆成四张重复页面",
    teacher_script: "（保留上一页的真实主题卡墙，教师不另换转场页。）刚才这些作品，写过相遇、等待，也写过共同生活里的选择和波折。今天再读一个更早的故事。它不只写相遇，还由一位女子回望婚后的日子。先别急着回答，请看这三个问题；我们读完六章，再回来。",
    next_event_id: "E_FIRST_LISTEN",
  },
  {
    page_id: "N008", event_id: "E_FIRST_LISTEN", unit_role: "体验", visual: "全文/章内整读", minutes: 3,
    legacy_ids: ["S010"],
    title: "第一次完整听读｜第一至第三章",
    visible: "第一次完整听读｜第一至第三章\n氓之蚩蚩，抱布贸丝。匪来贸丝，来即我谋。\n送子涉淇，至于顿丘。匪我愆期，子无良媒。\n将子无怒，秋以为期。\n\n乘彼垝垣，以望复关。不见复关，泣涕涟涟。\n既见复关，载笑载言。尔卜尔筮，体无咎言。\n以尔车来，以我贿迁。\n\n桑之未落，其叶沃若。于嗟鸠兮，无食桑葚！\n于嗟女兮，无与士耽！士之耽兮，犹可说也。\n女之耽兮，不可说也！",
    function: "让前三章在不中断听读时保持远距可读",
    prerequisite: "学生已读三问并知道只留下一个停顿记号",
    input: "第一至第三章完整原诗",
    action: "随声音听读，中途不回答问题，只在停顿处轻点或画问号",
    artifact: "前三章中的个人停顿记号",
    listener: "听教师连续朗读，不在换页时讨论",
    change: ["尚未整体听见前半诗", "连续接收前三章", "留下可能的个人停顿处"],
    location: "教材原句旁",
    previous: "调用三问作为弱导航",
    next: "不中断进入第四至第六章",
    loss: "合并到一页会缩小原诗并损害后排可读性",
    framework: "不解释字词、不公布情绪标签",
    next_event_id: "E_FIRST_MARK",
  },
  {
    page_id: "N009", event_id: "E_FIRST_LISTEN", unit_role: "体验", visual: "全文/章内整读", minutes: 3,
    legacy_ids: ["S011"],
    title: "第一次完整听读｜第四至第六章",
    visible: "第一次完整听读｜第四至第六章\n桑之落矣，其黄而陨。自我徂尔，三岁食贫。\n淇水汤汤，渐车帷裳。女也不爽，士贰其行。\n士也罔极，二三其德。\n\n三岁为妇，靡室劳矣。夙兴夜寐，靡有朝矣。\n言既遂矣，至于暴矣。兄弟不知，咥其笑矣。\n静言思之，躬自悼矣。\n\n及尔偕老，老使我怨。淇则有岸，隰则有泮。\n总角之宴，言笑晏晏。信誓旦旦，不思其反。\n反是不思，亦已焉哉！",
    function: "让后三章在不中断听读时保持远距可读并完成六章整体接收",
    prerequisite: "前三章听读未被讲解打断",
    input: "第四至第六章完整原诗",
    action: "继续听读到结尾，再确认自己的一个停顿处",
    artifact: "六章范围内的个人停顿记号",
    listener: "一直听到‘亦已焉哉’，结束前不公开交流",
    change: ["只听见前半诗", "完成六章整体接收", "形成一个待表达的停顿处"],
    location: "教材原句旁",
    previous: "承接前三章连续听读",
    next: "同桌说出并保存停顿句",
    loss: "合并到一页会缩小原诗并损害后排可读性",
    framework: "不把换页虚构成第二个学习目标",
    next_event_id: "E_FIRST_MARK",
  },
  {
    page_id: "N010", event_id: "E_FIRST_MARK", unit_role: "交流", visual: "活动界面", minutes: 3,
    legacy_ids: ["S012"],
    title: "哪一句把你留了下来？",
    visible: "哪一句把你留了下来？\n抄下一句。\n接一句：我听见……｜我看见……｜我想问……\n同桌各说一次；听的人补记一个不同之处。",
    function: "把个人初听停顿转成可保存、可交流并在全文回读时调用的初读证据",
    prerequisite: "每人完成六章听读并拥有停顿记号或‘尚未找到’",
    input: "个人停顿记号和原诗",
    action: "每人抄一句并接一句自然话，同桌各说一次，听者补记差异",
    artifact: "初读停顿卡和同伴差异补记",
    listener: "听同桌说完，补记一项自己没有注意到的声音、画面或疑问",
    change: ["停顿只是私人记号", "形成可读的初读证据并经过一次倾听", "全文回读时可核验理解变化"],
    location: "学习单·第一次完整听读",
    previous: "调用完整听读形成的停顿",
    next: "全文回读时重读原停顿并写下变化",
    loss: "没有保存和后用，完整听读只留下转瞬感受",
    framework: "允许‘尚未找到’，不强迫预设情绪",
    teacher_script: "如果有一句把你留了下来，就抄下它，再接一句自然话：我听见、我看见，或者我想问。如果暂时没有，也请如实写‘尚未找到’，听同桌说完以后再决定要不要补一句。两个人都要说一次；听的人补记一个自己原先没有注意到的地方。",
    next_event_id: "E_FULL_TEXT_RETURN",
    deferred: { target_batch: "full_text_return", expected_use: "全文讲读后重读初听停顿并写出理解变化" },
  },
  {
    page_id: "N011", event_id: "E_CONTEXT", unit_role: "澄清", visual: "原文批注", minutes: 2,
    legacy_ids: ["S013"],
    title: "《诗经》与《卫风》",
    visible: "《诗经》与《卫风》\n我国最早的诗歌总集｜305篇\n风、雅、颂｜《氓》属于《卫风》\n一位女子，用第一人称回望婚姻经历\n同桌各用一句话说：谁在回望什么？",
    function: "在学生先听完整诗后补足继续逐句阅读所需的最小文本身份",
    prerequisite: "学生已听见六章并保留个人停顿",
    input: "教材题名、出处和学习提示",
    action: "在教材题名旁写下305、卫风、女子第一人称三个定位词",
    artifact: "三项文本身份旁批",
    listener: "听同桌用一句话复述‘谁在回望什么’，核对三个定位词",
    change: ["只凭声音接触作品", "获得最小作品身份", "能说出谁在回望何种经历"],
    location: "教材题名旁批",
    previous: "不打断第一次完整听读",
    next: "用四言节奏进入第一章句群",
    loss: "缺少体裁、出处和叙述主体会削弱后续语言判断",
    framework: "不在此倾倒完整文学史和手法术语",
    next_event_id: "E_RHYTHM",
  },
  {
    page_id: "N012", event_id: "E_RHYTHM", unit_role: "体验", visual: "原文批注", minutes: 2,
    legacy_ids: ["S014", "S015", "S016"],
    title: "先借四言节奏走进声音",
    visible: "先借四言节奏走进声音\n氓之／蚩蚩，抱布／贸丝。\n匪来／贸丝，来即／我谋。\n先读出行动，不把语意切碎。\n同桌互读；听见机械停顿，就问：谁做什么？再读一遍。",
    function: "让学生用基本四言节奏读顺第一句群，同时推迟尚未观察到的手法命名",
    prerequisite: "学生已知道女子第一人称回望并准备进入第一章",
    input: "第一章前两组原句和停顿示范",
    action: "教师范读一次，全班跟读一次，同桌去掉斜线互读一次",
    artifact: "一版保持语意连续的节奏标记",
    listener: "同桌指出一处机械停顿并用‘谁—做什么’帮助重读",
    change: ["四言可能被逐字点读", "能以基本节奏保持行动连贯", "为第一章句群讲读做好声音准备"],
    location: "教材第一章原句旁",
    previous: "调用最小作品身份和初听声音",
    next: "进入第一章外在印象与真实来意句群",
    loss: "没有声音支架，逐句解释容易变成断裂的字词翻译",
    framework: "易错字音随相应句群解决，不集中倾倒十词",
    next_event_id: "E_CHAPTER1_START",
  },
];

const eventOverrides = {
  E_RECALL_PERSONAL: {
    actions: ["每人先独立写1—3篇；45秒仍空白者翻目录、看隐藏提示条或先听后补"],
    listener_task: "静默检索；完成者继续扩展不同类型作品",
  },
  E_RECALL_GROUP: {
    actions: ["四人依次发言，每人15—20秒；记录者只记篇名与主题短语"],
    listener_task: "听者勾记一项自己未想到的作品或主题",
  },
  E_RECALL_CLASS: {
    actions: ["每组先贴贡献卡，再用20秒说新增作品或不同主题；八组公开、贴卡与换组最多4分钟"],
    listener_task: "全班每人勾下一项新增内容",
  },
  E_THEME_MAP: {
    actions: ["全班静看八张贡献卡；一名学生试移一张并说理由；教师只沿现场材料串联；全班核对、补充或纠正"],
    listener_task: "核对每个主题是否能追溯到现场作品",
  },
  E_FIRST_LISTEN: {
    actions: ["六章不中断听读；学生只在停顿处留点、问号或短语"],
    listener_task: "完整听到结尾，不在换页处讨论",
  },
  E_FIRST_MARK: {
    actions: ["每人抄一句并写自然话；同桌各说一次，听者补记差异"],
    listener_task: "听同桌完整说完并补记一个不同之处",
  },
};

const futureEvents = [
  {
    event_id: "E_FULL_TEXT_RETURN", execution_order: 800, batch: "full_text_return",
    owner_page_ids: ["N010"], inputs: ["初读停顿卡"], actions: ["全文讲读后回看初读停顿并写理解变化"],
    artifacts: ["初读—再读修订记录"], locations: ["学习单·全文回读"], next_uses: ["进入三问总结"],
  },
  {
    event_id: "E_MARRIAGE_ROUND_TABLE", execution_order: 900, batch: "marriage_roundtable",
    owner_page_ids: ["N005"], inputs: ["班级爱情与婚姻文学主题谱"], actions: ["圆桌讨论回看开头主题谱并修订判断"],
    artifacts: ["个人婚姻提醒"], locations: ["学习单·婚姻圆桌"], next_uses: ["进入知识收纳"],
  },
  {
    event_id: "E_CHAPTER1_START", execution_order: 950, batch: "chapter_1",
    owner_page_ids: ["N012"], inputs: ["第一章节奏标记"], actions: ["调用节奏标记进入第一章逐句讲读"],
    artifacts: ["第一章原句旁批"], locations: ["教材第一章原句旁"], next_uses: ["进入第二章"],
  },
  {
    event_id: "E_FUTURE_TERMINAL", execution_order: 1000, batch: "final",
    owner_page_ids: ["N012"], inputs: ["全文终读后的个人理解"], actions: ["交付退出条"],
    artifacts: ["退出条"], locations: ["班级收集袋或学生学习档案"], next_uses: [], terminal_sink: true,
  },
];

const payload = { pages, event_overrides: eventOverrides, future_events: futureEvents };

if (require.main === module) process.stdout.write(`${JSON.stringify(payload)}\n`);

module.exports = payload;
