#!/usr/bin/env node
"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
function requireGlobal(name) { try { return require(name); } catch (_) { return require(path.join(process.env.NODE_GLOBAL_ROOT || "/usr/local/node-v22.22.2-linux-x64/lib/node_modules", name)); } }
const pptxgen = requireGlobal("pptxgenjs");
const npmRoot = process.env.NODE_GLOBAL_ROOT || "/usr/local/node-v22.22.2-linux-x64/lib/node_modules";
const JSZip = require(path.join(npmRoot, "pptxgenjs", "node_modules", "jszip"));
const source = require("./meng_v62/content/chapter_4");
const { validate } = require("./verify_meng_v62_chapter4");
const { PROJECT_ROOT, stageDir, assertV62OutputPath } = require("./meng_v62/paths");

const SNAPSHOT = path.join(stageDir(), "chapter_4", "package", "06_氓_V63第四章课程数据快照.json");
const OUT = assertV62OutputPath(path.join(stageDir(), "chapter_4", "pptx"));
const PPTX = assertV62OutputPath(path.join(OUT, "04_氓_V63第四章课堂课件.pptx"));
const MANIFEST = assertV62OutputPath(path.join(OUT, "chapter4_pptx_manifest.json"));
const W = 13.333, H = 7.5;
const FONT_HEAD = "Noto Serif CJK SC", FONT_BODY = "Noto Sans CJK SC", FONT_TEXT = "Noto Serif CJK SC";
const C = { ink:"29241F", ink2:"51483F", paper:"F6F0E5", paper2:"FFFCF7", warm:"E5DAC9", red:"9C4538", redSoft:"F0DDD5", river:"456F7C", riverSoft:"DDE9E9", leaf:"647752", leafSoft:"E1E7D9", gold:"AC8550", goldSoft:"EFE4D2", plum:"75515E", plumSoft:"EADDE1", muted:"766D63", night:"28241F", night2:"38312A", yellow:"B58A35", yellowSoft:"EFE4C5" };
function sha256(filePath) { return crypto.createHash("sha256").update(fs.readFileSync(filePath)).digest("hex"); }
function presentation() { const p = new pptxgen(); p.defineLayout({ name:"MENG_WIDE", width:W, height:H }); p.layout="MENG_WIDE"; p.author="语文备课系统"; p.title="《氓》V6.3第四章课堂课件"; p.subject="第四章由婚后经历进入责任判断"; p.lang="zh-CN"; p.theme={headFontFace:FONT_HEAD,bodyFontFace:FONT_BODY,lang:"zh-CN"}; return p; }
function addText(s,t,o={}) { s.addText(t,{x:.72,y:.52,w:11.9,h:.5,margin:0,fontFace:FONT_BODY,fontSize:28,color:C.ink,valign:"mid",...o}); }
function rect(s,p,x,y,w,h,fill,lineColor=fill,radius=false,transparency=0,width=1) { s.addShape(radius?p.shapes.ROUNDED_RECTANGLE:p.shapes.RECTANGLE,{x,y,w,h,fill:{color:fill,transparency},line:{color:lineColor,width},...(radius?{rectRadius:.05}:{})}); }
function line(s,p,x,y,w,color,width=1,transparency=0) { s.addShape(p.shapes.LINE,{x,y,w,h:0,line:{color,width,transparency}}); }
function base(s,p,dark=false) { s.background={color:dark?C.night:C.paper}; rect(s,p,0,0,W,.12,dark?C.yellow:C.ink); }
function title(s,t,o={}) { addText(s,t,{x:.76,y:.38,w:10.35,h:.62,fontFace:FONT_HEAD,fontSize:33,bold:true,...o}); addText(s,"第四章　4 / 6",{x:10.78,y:.5,w:1.82,h:.3,fontSize:17.5,bold:true,color:o.color||C.red,align:"right"}); }
function notesFor(page) { const script=page.script; return [`【V6.3页ID】${page.page_id}｜${page.title}｜${page.minutes}分钟`,`【本页不可替代的意义】`,page.unique_function,`【删除本页会失去什么】`,page.deletion_loss,`【相邻合并测试】`,page.merge_test,`【教师逐字稿】`,script.teacher_spoken,`【场面与走位】`,script.scene,...script.stage_directions.map((item)=>`（${item}）`),`【时间盒】`,script.timeboxes.map((item)=>`${item.label}：${item.seconds}秒`).join("；"),`【现场分支】`,script.branches.map((item)=>`${item.kind}：${item.response}`).join("\n"),`【听者同步任务】`,script.listener_task,`【证据位置】`,script.evidence_location,`【回到人物和故事】`,page.story_return,`【后续真实调用】`,page.next_use,`【自然切页句】`,script.cut_line,`【声明边界】桌面排演稿；不声称真实学生已经理解、参与或学会。`].join("\n"); }
function addNotes(s,page){s.addNotes(notesFor(page));}

function renderC401(s,p,page){base(s,p);title(s,"第四章｜桑叶落下以后，诗写了哪些生活？");const lines=page.original_text.split("。").filter(Boolean).map((x)=>`${x}。`);rect(s,p,.88,1.18,11.57,4.65,C.paper2,C.warm,true,0,1.05);lines.forEach((text,index)=>addText(s,text,{x:1.15,y:1.5+index*.72,w:11.03,h:.49,fontFace:FONT_TEXT,fontSize:31.5,align:"center",color:index===0?C.yellow:C.ink,bold:index===0}));addText(s,"读完以后，只留下两处原文",{x:4.37,y:6.08,w:4.6,h:.34,fontFace:FONT_HEAD,fontSize:18.5,bold:true,color:C.muted,align:"center"});addText(s,"桑叶的新样子　｜　一句你听来像在判断的话",{x:1.35,y:6.48,w:10.63,h:.43,fontFace:FONT_HEAD,fontSize:25,bold:true,color:C.plum,align:"center"});addNotes(s,page);}
function renderC402(s,p,page){base(s,p,true);title(s,"沃若｜黄而陨：原来的想法，经得住这一落吗？",{color:C.paper});rect(s,p,.85,1.38,5.72,2.5,"333A31",C.leaf,true,0,1.05);rect(s,p,6.78,1.38,5.72,2.5,"3D372D",C.yellow,true,0,1.05);addText(s,"未落",{x:1.13,y:1.7,w:5.16,h:.34,fontSize:22,bold:true,color:C.leafSoft,align:"center"});addText(s,"桑之未落，其叶沃若。",{x:1.05,y:2.38,w:5.32,h:.57,fontFace:FONT_TEXT,fontSize:32,bold:true,color:C.leafSoft,align:"center"});addText(s,"落",{x:7.06,y:1.7,w:5.16,h:.34,fontSize:22,bold:true,color:C.yellowSoft,align:"center"});addText(s,"桑之落矣，其黄而陨。",{x:6.98,y:2.38,w:5.32,h:.57,fontFace:FONT_TEXT,fontSize:32,bold:true,color:C.yellowSoft,align:"center"});addText(s,"陨：坠落",{x:4.75,y:4.35,w:3.83,h:.38,fontSize:22,bold:true,color:C.warm,align:"center"});addText(s,"翻回原来的两种想法",{x:3.15,y:5.18,w:7.03,h:.48,fontFace:FONT_HEAD,fontSize:28,bold:true,color:C.paper,align:"center"});addText(s,"保留、改写，还是撤回？为什么？",{x:2.25,y:5.89,w:8.83,h:.48,fontFace:FONT_HEAD,fontSize:27,color:C.yellowSoft,align:"center"});addNotes(s,page);}
function renderC403(s,p,page){base(s,p);title(s,"三岁食贫｜淇水汤汤");rect(s,p,.88,1.32,5.63,2.12,C.goldSoft,C.gold,true,0,1.05);rect(s,p,6.82,1.32,5.63,2.12,C.riverSoft,C.river,true,0,1.05);addText(s,"自我徂尔，三岁食贫。",{x:1.05,y:2.02,w:5.3,h:.54,fontFace:FONT_TEXT,fontSize:31,bold:true,color:C.ink,align:"center"});addText(s,"淇水汤汤，渐车帷裳。",{x:6.99,y:2.02,w:5.3,h:.54,fontFace:FONT_TEXT,fontSize:31,bold:true,color:C.ink,align:"center"});addText(s,"徂：往　食贫：过贫苦生活",{x:1.0,y:3.75,w:5.38,h:.42,fontSize:22.5,bold:true,color:C.gold,align:"center"});addText(s,"汤汤 shāng shāng：水势浩大　渐 jiān：浸湿",{x:6.55,y:3.75,w:5.78,h:.42,fontSize:22,bold:true,color:C.river,align:"center"});addText(s,"一句把怎样的日子压在里面？",{x:.98,y:4.82,w:5.55,h:.52,fontFace:FONT_HEAD,fontSize:27,bold:true,color:C.gold,align:"center"});addText(s,"一句让哪一刻忽然展开？",{x:6.82,y:4.82,w:5.55,h:.52,fontFace:FONT_HEAD,fontSize:27,bold:true,color:C.river,align:"center"});addText(s,"让两句分别响一次，再写你看见的生活",{x:2.7,y:6.0,w:7.93,h:.38,fontSize:21,bold:true,color:C.plum,align:"center"});addNotes(s,page);}
function renderC404(s,p,page){base(s,p,true);title(s,"女也不爽，士贰其行",{color:C.paper});rect(s,p,1.0,1.45,11.33,1.55,"3A3430",C.plum,true,0,1.05);addText(s,"女也不爽，士贰其行。",{x:1.35,y:1.92,w:10.63,h:.58,fontFace:FONT_TEXT,fontSize:43,bold:true,color:C.paper,align:"center"});addText(s,"爽：差错　｜　贰：不专一、前后不一",{x:2.5,y:3.52,w:8.33,h:.4,fontSize:24,bold:true,color:C.warm,align:"center"});addText(s,"只用这一句，说清",{x:4.42,y:4.42,w:4.5,h:.43,fontFace:FONT_HEAD,fontSize:25,color:C.plumSoft,align:"center"});addText(s,"谁怎样？　谁又怎样？",{x:2.15,y:5.25,w:9.03,h:.55,fontFace:FONT_HEAD,fontSize:36,bold:true,color:C.paper,align:"center"});addNotes(s,page);}
function renderC405(s,p,page){base(s,p);title(s,"士也罔极，二三其德");rect(s,p,.92,1.4,11.49,1.45,C.redSoft,C.red,true,0,1.05);addText(s,"士也罔极，二三其德。",{x:1.25,y:1.83,w:10.83,h:.57,fontFace:FONT_TEXT,fontSize:42,bold:true,color:C.red,align:"center"});addText(s,"罔极：没有准则　｜　二三：反复无常",{x:2.43,y:3.35,w:8.47,h:.42,fontSize:24,bold:true,color:C.ink2,align:"center"});line(s,p,2.6,4.22,8.13,C.warm,1.3,0);addText(s,"若改成：‘他的行为多次改变’",{x:2.05,y:4.63,w:9.23,h:.45,fontFace:FONT_HEAD,fontSize:27,color:C.muted,align:"center"});addText(s,"哪一种更让你听见无定与反复？",{x:1.55,y:5.65,w:10.23,h:.55,fontFace:FONT_HEAD,fontSize:31,bold:true,color:C.plum,align:"center"});addNotes(s,page);}
function renderC406(s,p,page){base(s,p,true);title(s,"把第四章讲成一段：桑叶落下以后",{color:C.paper});const lines=page.original_text.split("。").filter(Boolean).map((x)=>`${x}。`);rect(s,p,.78,1.2,7.72,5.14,C.night2,C.yellow,true,0,1.05);lines.forEach((text,index)=>addText(s,text,{x:1.04,y:1.61+index*.82,w:7.2,h:.46,fontFace:FONT_TEXT,fontSize:29,color:C.paper,align:"center"}));addText(s,"桑叶怎样变？",{x:8.82,y:1.67,w:3.78,h:.48,fontFace:FONT_HEAD,fontSize:25,bold:true,color:C.yellowSoft,align:"center"});addText(s,"她过着怎样的日子？",{x:8.82,y:2.83,w:3.78,h:.78,fontFace:FONT_HEAD,fontSize:24.5,bold:true,color:C.paper,align:"center"});addText(s,"她最后怎样\n说两个人？",{x:8.82,y:4.18,w:3.78,h:.92,fontFace:FONT_HEAD,fontSize:25,bold:true,color:C.plumSoft,align:"center"});addText(s,"合书以后，把三层连成一段",{x:8.82,y:5.65,w:3.78,h:.38,fontSize:20,bold:true,color:C.warm,align:"center"});addText(s,"故事轨道｜第四格",{x:.82,y:6.62,w:2.12,h:.3,fontSize:18,bold:true,color:C.yellowSoft});line(s,p,3.2,6.86,8.73,C.yellow,2,0);addNotes(s,page);}

function validateObjects(p,n){const errors=[];if(p._slides.length!==n)errors.push(`slides ${p._slides.length}/${n}`);p._slides.forEach((slide,index)=>{if(!slide._slideObjects.some((item)=>item._type==="notes"))errors.push(`slide ${index+1} missing notes`);slide._slideObjects.forEach((item,objectIndex)=>{const options=item.options||{};if([options.x,options.y,options.w,options.h].every((value)=>typeof value==="number")&&(options.x<-.01||options.y<-.01||options.x+options.w>W+.01||options.y+options.h>H+.01))errors.push(`slide ${index+1} object ${objectIndex+1} out of bounds`);});});if(errors.length)throw new Error(errors.join("\n"));}
async function repairNotesMaster(filePath){const archive=await JSZip.loadAsync(fs.readFileSync(filePath));const entry=archive.file("ppt/presentation.xml");let xml=await entry.async("string");const match=xml.match(/<p:notesMasterIdLst>[\s\S]*?<\/p:notesMasterIdLst>/);if(match){xml=xml.replace(match[0],"");xml=xml.replace(/(<p:sldMasterIdLst>[\s\S]*?<\/p:sldMasterIdLst>)/,`$1${match[0]}`);}archive.file("ppt/presentation.xml",xml);fs.writeFileSync(filePath,await archive.generateAsync({type:"nodebuffer",compression:"DEFLATE"}));}
async function main(){const verification=validate(source);if(!verification.ok)throw new Error(JSON.stringify(verification.errors));const snapshot=JSON.parse(fs.readFileSync(SNAPSHOT,"utf8"));if(snapshot.source_sha256!==sha256(path.join(PROJECT_ROOT,"scripts","meng_v62","content","chapter_4.js")))throw new Error("stale snapshot");const pageMap=new Map(snapshot.pages.map((item)=>[item.page_id,item]));const plan=[["C401",renderC401,"完整章声与判断转折初稿"],["C402",renderC402,"桑叶前后修订"],["C403",renderC403,"多年与水景时间体验"],["C404",renderC404,"责任证据席"],["C405",renderC405,"二三替换听辨"],["C406",renderC406,"撤答整章重建"]];const pages=plan.map(([id,renderer,duty],index)=>({...pageMap.get(id),renderer,duty,physicalIndex:index+1}));const pres=presentation();pages.forEach((page)=>page.renderer(pres.addSlide(),pres,page));validateObjects(pres,pages.length);fs.mkdirSync(OUT,{recursive:true});await pres.writeFile({fileName:PPTX,compression:true});await repairNotesMaster(PPTX);const manifest={schema_version:"1.1",module_id:source.module_id,version:source.version,artifact:path.relative(PROJECT_ROOT,PPTX).split(path.sep).join("/"),sha256:sha256(PPTX),source_snapshot_sha256:sha256(SNAPSHOT),physical_slides:pages.map((page)=>({physical_index:page.physicalIndex,page_id:page.page_id,primary_visual_duty:page.duty,unique_function:page.unique_function})),illustration_policy:"no_character_illustration_until_all_lesson_functions_are_frozen",claim_boundary:"chapter4_candidate_not_classroom_observed"};fs.writeFileSync(MANIFEST,`${JSON.stringify(manifest,null,2)}\n`);process.stdout.write(`V63_CHAPTER4_PPTX_OK slides=${pages.length} pptx=${PPTX}\n`);}
main().catch((error)=>{process.stderr.write(`${error.stack||error}\n`);process.exit(1);});
