#!/usr/bin/env node
"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
function requireGlobal(name) { try { return require(name); } catch (_) { return require(path.join(process.env.NODE_GLOBAL_ROOT || "/usr/local/node-v22.22.2-linux-x64/lib/node_modules", name)); } }
const pptxgen = requireGlobal("pptxgenjs");
const npmRoot = process.env.NODE_GLOBAL_ROOT || "/usr/local/node-v22.22.2-linux-x64/lib/node_modules";
const JSZip = require(path.join(npmRoot, "pptxgenjs", "node_modules", "jszip"));
const source = require("./meng_v62/content/chapter_2");
const { validate } = require("./verify_meng_v62_chapter2");
const { PROJECT_ROOT, stageDir, assertV62OutputPath } = require("./meng_v62/paths");
const SNAPSHOT = path.join(stageDir(), "chapter_2", "package", "06_氓_V62第二章课程数据快照.json");
const OUT = assertV62OutputPath(path.join(stageDir(), "chapter_2", "pptx"));
const PPTX = assertV62OutputPath(path.join(OUT, "04_氓_V62第二章课堂课件.pptx"));
const MANIFEST = assertV62OutputPath(path.join(OUT, "chapter2_pptx_manifest.json"));
const W = 13.333, H = 7.5;
const FONT_HEAD = "Noto Serif CJK SC", FONT_BODY = "Noto Sans CJK SC", FONT_TEXT = "Noto Serif CJK SC";
const C = { ink:"29241F", ink2:"51483F", paper:"F6F0E5", paper2:"FFFCF7", warm:"E5DAC9", warm2:"D2C1AA", red:"9C4538", redSoft:"F0DDD5", river:"456F7C", riverSoft:"DDE9E9", leaf:"647752", leafSoft:"E1E7D9", gold:"AC8550", goldSoft:"EFE4D2", white:"FFFFFF", muted:"766D63", night:"28241F", night2:"38312A" };
function sha256(p) { return crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex"); }
function presentation() { const p=new pptxgen(); p.defineLayout({name:"MENG_WIDE",width:W,height:H}); p.layout="MENG_WIDE"; p.author="语文备课系统"; p.title="《氓》V6.2第二章课堂课件"; p.subject="第二章逐句讲读"; p.lang="zh-CN"; p.theme={headFontFace:FONT_HEAD,bodyFontFace:FONT_BODY,lang:"zh-CN"}; return p; }
function addText(s,t,o={}) { s.addText(t,{x:.72,y:.52,w:11.9,h:.5,margin:0,fontFace:FONT_BODY,fontSize:28,color:C.ink,valign:"mid",...o}); }
function rect(s,p,x,y,w,h,fill,lineColor=fill,radius=false,transparency=0,width=1) { s.addShape(radius?p.shapes.ROUNDED_RECTANGLE:p.shapes.RECTANGLE,{x,y,w,h,fill:{color:fill,transparency},line:{color:lineColor,width},...(radius?{rectRadius:.05}:{})}); }
function line(s,p,x,y,w,color,width=1,transparency=0,dash="solid") { s.addShape(p.shapes.LINE,{x,y,w,h:0,line:{color,width,transparency,dashType:dash}}); }
function dot(s,p,x,y,d,color,transparency=0) { s.addShape(p.shapes.OVAL,{x,y,w:d,h:d,fill:{color,transparency},line:{color,transparency}}); }
function base(s,p,dark=false) { s.background={color:dark?C.night:C.paper}; rect(s,p,0,0,W,.12,dark?C.gold:C.ink); }
function title(s,t,o={}) { addText(s,t,{x:.76,y:.38,w:10.35,h:.62,fontFace:FONT_HEAD,fontSize:33,bold:true,...o}); addText(s,"第二章　2 / 6",{x:10.78,y:.5,w:1.82,h:.3,fontSize:17.5,bold:true,color:o.color||C.red,align:"right"}); }
function notesFor(p) { const s=p.script; return [`【V6.3页ID】${p.page_id}｜${p.title}｜${p.minutes}分钟`,`【本页不可替代的意义】`,p.unique_function,`【删除本页会失去什么】`,p.deletion_loss,`【相邻合并测试】`,p.merge_test,`【教师逐字稿】`,s.teacher_spoken,`【场面与走位】`,s.scene,...s.stage_directions.map(x=>`（${x}）`),`【时间盒】`,s.timeboxes.map(x=>`${x.label}：${x.seconds}秒`).join("；"),`【现场分支】`,s.branches.map(x=>`${x.kind}：${x.response}`).join("\n"),`【听者同步任务】`,s.listener_task,`【证据位置】`,s.evidence_location,`【回到人物和故事】`,p.story_return,`【后续真实调用】`,p.next_use,`【自然切页句】`,s.cut_line,`【声明边界】桌面排演稿；不声称真实学生已经理解、参与或学会。`].join("\n"); }
function addNotes(s,p){s.addNotes(notesFor(p));}

function renderC201(s,p,page){base(s,p);title(s,"第二章｜约定以后，故事怎样继续？");const ls=page.original_text.split("。").filter(Boolean).map(x=>`${x}。`);rect(s,p,.88,1.18,11.57,5.5,C.paper2,C.warm,true,0,1.05);ls.forEach((x,i)=>addText(s,x,{x:1.15,y:1.62+i*.9,w:11.03,h:.55,fontFace:FONT_TEXT,fontSize:34,align:"center"}));addNotes(s,page);}
function renderC202(s,p,page){base(s,p);title(s,"“不见”与“既见”，两句怎样转过去？");const ls=page.original_text.split("。").filter(Boolean);const rows=[[ls[0],C.river,C.riverSoft],[ls[1],C.red,C.redSoft]];rows.forEach(([x,color,fill],i)=>{const y=1.35+i*1.55;rect(s,p,.95,y,11.43,1.16,fill,color,true,0,1.05);addText(s,`${x}。`,{x:1.25,y:y+.28,w:10.83,h:.56,fontFace:FONT_TEXT,fontSize:40,bold:true,color,align:"center"});});addText(s,"哪些词彼此照应？　你想让声音从哪里转过去？",{x:1.15,y:5.16,w:11.03,h:.58,fontFace:FONT_HEAD,fontSize:28,bold:true,color:C.ink,align:"center"});addText(s,"让原词先站出来，再让耳朵听见它。",{x:2.15,y:6.1,w:9.03,h:.4,fontFace:FONT_HEAD,fontSize:21,color:C.muted,align:"center"});addNotes(s,page);}
function renderC204(s,p,page){base(s,p);title(s,"卜筮以后，婚事怎样落到生活里？");const ls=page.original_text.split("。").filter(Boolean);addText(s,`${ls[0]}。`,{x:.9,y:1.22,w:11.53,h:.62,fontFace:FONT_TEXT,fontSize:39,bold:true,align:"center"});const terms=[["卜｜龟甲",C.gold,C.goldSoft],["筮｜蓍草",C.leaf,C.leafSoft],["体｜兆象",C.river,C.riverSoft],["咎言｜不祥之语",C.red,C.redSoft]];terms.forEach(([label,color,fill],i)=>{const x=.92+i*3.06;rect(s,p,x,2.12,2.71,.74,fill,color,true,0,1);addText(s,label,{x:x+.15,y:2.34,w:2.41,h:.29,fontFace:FONT_HEAD,fontSize:20.5,bold:true,color,align:"center"});});addText(s,"这次占问，写出了怎样的结果？",{x:2.2,y:3.34,w:8.93,h:.5,fontFace:FONT_HEAD,fontSize:27,bold:true,align:"center"});line(s,p,1.1,4.16,11.13,C.warm2,1);addText(s,`${ls[1]}。`,{x:.9,y:4.45,w:11.53,h:.62,fontFace:FONT_TEXT,fontSize:39,bold:true,align:"center"});addText(s,"“以尔”与“以我”，各是谁的动作？",{x:2.2,y:5.62,w:8.93,h:.5,fontFace:FONT_HEAD,fontSize:27,bold:true,align:"center"});addNotes(s,page);}
function renderC206(s,p,page){base(s,p,true);title(s,"把等待到迁移，讲成一段故事",{color:C.paper});const ls=page.original_text.split("。").filter(Boolean).map(x=>`${x}。`);rect(s,p,.78,1.2,7.72,4.86,C.night2,C.gold,true,0,1.05);ls.forEach((x,i)=>addText(s,x,{x:1.04,y:1.6+i*.78,w:7.2,h:.45,fontFace:FONT_TEXT,fontSize:28.5,color:C.paper,align:"center"}));addText(s,"她怎样等？",{x:8.9,y:1.72,w:3.68,h:.48,fontFace:FONT_HEAD,fontSize:27,bold:true,color:C.gold,align:"center"});addText(s,"见与不见，\n怎样改变她？",{x:8.9,y:2.75,w:3.68,h:.95,fontFace:FONT_HEAD,fontSize:26,bold:true,color:C.paper,align:"center"});addText(s,"婚事怎样\n走到迁移？",{x:8.9,y:4.15,w:3.68,h:.95,fontFace:FONT_HEAD,fontSize:26,bold:true,color:C.riverSoft,align:"center"});addText(s,"故事轨道",{x:.78,y:6.43,w:1.35,h:.3,fontSize:17.5,bold:true,color:C.gold});for(let i=0;i<6;i++){const x=2.02+i*1.7;line(s,p,x,6.74,1.2,i<2?C.gold:C.muted,i<2?2:1,i<2?0:35);addText(s,String(i+1),{x:x+.42,y:6.36,w:.35,h:.24,fontSize:14,color:i<2?C.gold:C.muted,align:"center"});}addNotes(s,page);}
function validateObjects(p,n){const e=[];if(p._slides.length!==n)e.push(`slides ${p._slides.length}/${n}`);p._slides.forEach((s,i)=>{if(!s._slideObjects.some(x=>x._type==="notes"))e.push(`slide ${i+1} missing notes`);s._slideObjects.forEach((x,j)=>{const o=x.options||{};if([o.x,o.y,o.w,o.h].every(v=>typeof v==="number")&&(o.x<-.01||o.y<-.01||o.x+o.w>W+.01||o.y+o.h>H+.01))e.push(`slide ${i+1} object ${j+1} out of bounds`);});});if(e.length)throw new Error(e.join("\n"));}
async function repairNotesMaster(f){const z=await JSZip.loadAsync(fs.readFileSync(f));const e=z.file("ppt/presentation.xml");let x=await e.async("string");const m=x.match(/<p:notesMasterIdLst>[\s\S]*?<\/p:notesMasterIdLst>/);if(m){x=x.replace(m[0],"");x=x.replace(/(<p:sldMasterIdLst>[\s\S]*?<\/p:sldMasterIdLst>)/,`$1${m[0]}`);}z.file("ppt/presentation.xml",x);fs.writeFileSync(f,await z.generateAsync({type:"nodebuffer",compression:"DEFLATE"}));}
async function main(){const v=validate(source);if(!v.ok)throw new Error(JSON.stringify(v.errors));const snap=JSON.parse(fs.readFileSync(SNAPSHOT,"utf8"));if(snap.source_sha256!==sha256(path.join(PROJECT_ROOT,"scripts","meng_v62","content","chapter_2.js")))throw new Error("stale snapshot");const map=new Map(snap.pages.map(x=>[x.page_id,x]));const plan=[["C201",renderC201,"完整章声与读后视线"],["C202",renderC202,"原词对照与闭眼听辨"],["C204",renderC204,"占问边界与双方迁移动作"],["C206",renderC206,"撤答故事重建"]];const pages=plan.map(([id,r,d],i)=>({...map.get(id),renderer:r,duty:d,physicalIndex:i+1}));const pres=presentation();pages.forEach(x=>x.renderer(pres.addSlide(),pres,x));validateObjects(pres,pages.length);fs.mkdirSync(OUT,{recursive:true});await pres.writeFile({fileName:PPTX,compression:true});await repairNotesMaster(PPTX);const manifest={schema_version:"1.1",module_id:source.module_id,version:source.version,artifact:path.relative(PROJECT_ROOT,PPTX).split(path.sep).join("/"),sha256:sha256(PPTX),source_snapshot_sha256:sha256(SNAPSHOT),physical_slides:pages.map(x=>({physical_index:x.physicalIndex,page_id:x.page_id,primary_visual_duty:x.duty,unique_function:x.unique_function})),illustration_policy:"no_character_illustration_until_all_lesson_functions_are_frozen",claim_boundary:"chapter2_candidate_not_classroom_observed"};fs.writeFileSync(MANIFEST,`${JSON.stringify(manifest,null,2)}\n`);process.stdout.write(`V63_CHAPTER2_PPTX_OK slides=${pages.length} pptx=${PPTX}\n`);}
main().catch(e=>{process.stderr.write(`${e.stack||e}\n`);process.exit(1);});
