#!/usr/bin/env node
"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
function requireGlobal(name) { try { return require(name); } catch (_) { return require(path.join(process.env.NODE_GLOBAL_ROOT || "/usr/local/node-v22.22.2-linux-x64/lib/node_modules", name)); } }
const pptxgen = requireGlobal("pptxgenjs");
const npmRoot = process.env.NODE_GLOBAL_ROOT || "/usr/local/node-v22.22.2-linux-x64/lib/node_modules";
const JSZip = require(path.join(npmRoot, "pptxgenjs", "node_modules", "jszip"));
const source = require("./meng_v62/content/chapter_3");
const { validate } = require("./verify_meng_v62_chapter3");
const { PROJECT_ROOT, stageDir, assertV62OutputPath } = require("./meng_v62/paths");
const SNAPSHOT = path.join(stageDir(), "chapter_3", "package", "06_氓_V63第三章课程数据快照.json");
const OUT = assertV62OutputPath(path.join(stageDir(), "chapter_3", "pptx"));
const PPTX = assertV62OutputPath(path.join(OUT, "04_氓_V63第三章课堂课件.pptx"));
const MANIFEST = assertV62OutputPath(path.join(OUT, "chapter3_pptx_manifest.json"));
const W = 13.333, H = 7.5;
const FONT_HEAD = "Noto Serif CJK SC", FONT_BODY = "Noto Sans CJK SC", FONT_TEXT = "Noto Serif CJK SC";
const C = { ink:"29241F", ink2:"51483F", paper:"F6F0E5", paper2:"FFFCF7", warm:"E5DAC9", warm2:"D2C1AA", red:"9C4538", redSoft:"F0DDD5", river:"456F7C", riverSoft:"DDE9E9", leaf:"647752", leafSoft:"E1E7D9", gold:"AC8550", goldSoft:"EFE4D2", plum:"75515E", plumSoft:"EADDE1", white:"FFFFFF", muted:"766D63", night:"28241F", night2:"38312A" };
function sha256(p) { return crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex"); }
function presentation() { const p = new pptxgen(); p.defineLayout({ name:"MENG_WIDE", width:W, height:H }); p.layout="MENG_WIDE"; p.author="语文备课系统"; p.title="《氓》V6.3第三章课堂课件"; p.subject="第三章由桑叶进入劝告与处境对照"; p.lang="zh-CN"; p.theme={headFontFace:FONT_HEAD,bodyFontFace:FONT_BODY,lang:"zh-CN"}; return p; }
function addText(s,t,o={}) { s.addText(t,{x:.72,y:.52,w:11.9,h:.5,margin:0,fontFace:FONT_BODY,fontSize:28,color:C.ink,valign:"mid",...o}); }
function rect(s,p,x,y,w,h,fill,lineColor=fill,radius=false,transparency=0,width=1) { s.addShape(radius?p.shapes.ROUNDED_RECTANGLE:p.shapes.RECTANGLE,{x,y,w,h,fill:{color:fill,transparency},line:{color:lineColor,width},...(radius?{rectRadius:.05}:{})}); }
function line(s,p,x,y,w,color,width=1,transparency=0) { s.addShape(p.shapes.LINE,{x,y,w,h:0,line:{color,width,transparency}}); }
function base(s,p,dark=false) { s.background={color:dark?C.night:C.paper}; rect(s,p,0,0,W,.12,dark?C.leaf:C.ink); }
function title(s,t,o={}) { addText(s,t,{x:.76,y:.38,w:10.35,h:.62,fontFace:FONT_HEAD,fontSize:33,bold:true,...o}); addText(s,"第三章　3 / 6",{x:10.78,y:.5,w:1.82,h:.3,fontSize:17.5,bold:true,color:o.color||C.red,align:"right"}); }
function notesFor(p) { const s=p.script; return [`【V6.3页ID】${p.page_id}｜${p.title}｜${p.minutes}分钟`,`【本页不可替代的意义】`,p.unique_function,`【删除本页会失去什么】`,p.deletion_loss,`【相邻合并测试】`,p.merge_test,`【教师逐字稿】`,s.teacher_spoken,`【场面与走位】`,s.scene,...s.stage_directions.map(x=>`（${x}）`),`【时间盒】`,s.timeboxes.map(x=>`${x.label}：${x.seconds}秒`).join("；"),`【现场分支】`,s.branches.map(x=>`${x.kind}：${x.response}`).join("\n"),`【听者同步任务】`,s.listener_task,`【证据位置】`,s.evidence_location,`【回到人物和故事】`,p.story_return,`【后续真实调用】`,p.next_use,`【自然切页句】`,s.cut_line,`【声明边界】桌面排演稿；不声称真实学生已经理解、参与或学会。`].join("\n"); }
function addNotes(s,p){s.addNotes(notesFor(p));}

function renderC301(s,p,page){base(s,p);title(s,"第三章｜迁嫁以后，诗先让什么进入眼前？");const ls=page.original_text.split("。").filter(Boolean).map(x=>`${x}。`);rect(s,p,.88,1.18,11.57,4.65,C.paper2,C.warm,true,0,1.05);ls.forEach((x,i)=>addText(s,x,{x:1.15,y:1.5+i*.72,w:11.03,h:.49,fontFace:FONT_TEXT,fontSize:31.5,align:"center",color:i===0?C.leaf:C.ink,bold:i===0}));addText(s,"读完以后，只留下两处原文",{x:4.37,y:6.08,w:4.6,h:.34,fontFace:FONT_HEAD,fontSize:18.5,bold:true,color:C.muted,align:"center"});addText(s,"眼前先出现什么？　哪一句开始像在劝告？",{x:1.5,y:6.48,w:10.33,h:.43,fontFace:FONT_HEAD,fontSize:25,bold:true,color:C.plum,align:"center"});addNotes(s,page);}
function renderC302(s,p,page){base(s,p);title(s,"桑之未落，其叶沃若");rect(s,p,.82,1.18,11.7,1.18,C.leafSoft,C.leaf,true,0,1.05);addText(s,page.original_text,{x:1.08,y:1.49,w:11.18,h:.52,fontFace:FONT_TEXT,fontSize:43,bold:true,color:C.leaf,align:"center"});addText(s,"沃若：润泽的样子",{x:4.25,y:2.72,w:4.83,h:.38,fontSize:23,bold:true,color:C.ink2,align:"center"});addText(s,"这片桑叶，有怎样的色泽、质地和生命感？",{x:1.45,y:3.55,w:10.43,h:.5,fontFace:FONT_HEAD,fontSize:29,bold:true,color:C.ink,align:"center"});addText(s,"它可能让你想到什么？",{x:2.55,y:4.68,w:8.23,h:.5,fontFace:FONT_HEAD,fontSize:31,bold:true,color:C.red,align:"center"});addText(s,"两种可能，先都留下。",{x:3.55,y:5.84,w:6.23,h:.45,fontFace:FONT_HEAD,fontSize:25,color:C.leaf,align:"center"});addNotes(s,page);}
function renderC303(s,p,page){base(s,p,true);title(s,"两声‘于嗟’，劝告怎样来到人身边？",{color:C.paper});const a=["桑之未落，其叶沃若。","于嗟鸠兮，无食桑葚！","于嗟女兮，无与士耽！"];rect(s,p,.86,1.28,11.61,3.15,"343A31",C.leaf,true,0,1.05);a.forEach((x,i)=>addText(s,x,{x:1.12,y:1.58+i*.72,w:11.09,h:.48,fontFace:FONT_TEXT,fontSize:31,color:i===2?C.plumSoft:C.paper,align:"center",bold:i>0}));addText(s,"于嗟 xū jiē　｜　无同“毋”　｜　耽：沉溺",{x:1.0,y:4.65,w:11.33,h:.4,fontSize:22.5,bold:true,color:C.warm,align:"center"});addText(s,"两声‘于嗟’，从谁来到谁？",{x:.92,y:5.38,w:5.75,h:.48,fontFace:FONT_HEAD,fontSize:26.5,bold:true,color:C.goldSoft,align:"center"});addText(s,"若蒙住前两句，只听最后一句，少了什么？",{x:6.68,y:5.32,w:5.75,h:.62,fontFace:FONT_HEAD,fontSize:25,bold:true,color:C.plumSoft,align:"center"});addNotes(s,page);}
function renderC304(s,p,page){base(s,p,true);title(s,"若只留下‘于嗟女兮’，你听见的还一样吗？",{color:C.paper});const a=["桑之未落，其叶沃若。","于嗟鸠兮，无食桑葚！","于嗟女兮，无与士耽！"];rect(s,p,.88,1.45,5.75,3.82,"343A31",C.leaf,true,0,1.05);rect(s,p,6.85,1.45,5.6,3.82,"3D3336",C.plum,true,0,1.05);addText(s,"A｜原诗",{x:1.15,y:1.75,w:5.23,h:.35,fontSize:23,bold:true,color:C.leafSoft,align:"center"});a.forEach((x,i)=>addText(s,x,{x:1.15,y:2.35+i*.75,w:5.23,h:.46,fontFace:FONT_TEXT,fontSize:27,color:C.paper,align:"center",bold:i===2}));addText(s,"B｜只留下直劝",{x:7.12,y:1.75,w:5.06,h:.35,fontSize:23,bold:true,color:C.plumSoft,align:"center"});addText(s,a[2],{x:7.18,y:3.05,w:4.94,h:.55,fontFace:FONT_TEXT,fontSize:30,bold:true,color:C.paper,align:"center"});addText(s,"闭上眼睛听两遍",{x:3.5,y:5.7,w:6.33,h:.45,fontFace:FONT_HEAD,fontSize:27,bold:true,color:C.goldSoft,align:"center"});addText(s,"哪一种画面、声音或情绪，在B里消失了？",{x:1.25,y:6.28,w:10.83,h:.45,fontFace:FONT_HEAD,fontSize:25,color:C.warm,align:"center"});addNotes(s,page);}
function renderC305(s,p,page){base(s,p);title(s,"同是‘耽’，两个人都能脱身吗？");const ls=page.original_text.split(/[！。]/u).filter(Boolean);const cols=[[ls[0],C.river,C.riverSoft],[ls[1],C.plum,C.plumSoft]];cols.forEach(([x,color,fill],i)=>{const xx=.88+i*5.98;rect(s,p,xx,1.35,5.62,1.25,fill,color,true,0,1.05);addText(s,`${x}${i===0?"。":"！"}`,{x:xx+.22,y:1.7,w:5.18,h:.49,fontFace:FONT_TEXT,fontSize:31,bold:true,color,align:"center"});});addText(s,"说（tuō）：同“脱”，摆脱、脱身",{x:3.45,y:2.92,w:6.43,h:.4,fontSize:23,bold:true,color:C.ink2,align:"center"});addText(s,"相同的词是什么？",{x:.95,y:3.78,w:5.55,h:.5,fontFace:FONT_HEAD,fontSize:27,bold:true,color:C.river,align:"center"});addText(s,"真正改变结果的词是什么？",{x:6.83,y:3.78,w:5.55,h:.5,fontFace:FONT_HEAD,fontSize:27,bold:true,color:C.plum,align:"center"});rect(s,p,1.25,4.78,10.83,1.2,C.goldSoft,C.gold,true,0,1.05);addText(s,"这两句明写了什么，还没有写什么？",{x:1.58,y:5.12,w:10.17,h:.48,fontFace:FONT_HEAD,fontSize:28,bold:true,color:C.gold,align:"center"});addNotes(s,page);}
function renderC306(s,p,page){base(s,p,true);title(s,"把五句诗，讲成她回望中的一段话",{color:C.paper});const ls=page.original_text.split("。").filter(Boolean).map(x=>`${x}。`);rect(s,p,.78,1.2,7.72,5.14,C.night2,C.leaf,true,0,1.05);ls.forEach((x,i)=>addText(s,x,{x:1.04,y:1.61+i*.82,w:7.2,h:.46,fontFace:FONT_TEXT,fontSize:29,color:C.paper,align:"center"}));addText(s,"眼前先出现什么？",{x:8.82,y:1.67,w:3.78,h:.48,fontFace:FONT_HEAD,fontSize:25,bold:true,color:C.leafSoft,align:"center"});addText(s,"劝告怎样\n从物来到人？",{x:8.82,y:2.83,w:3.78,h:.92,fontFace:FONT_HEAD,fontSize:25,bold:true,color:C.paper,align:"center"});addText(s,"最后看见怎样的\n脱身处境？",{x:8.82,y:4.34,w:3.78,h:.92,fontFace:FONT_HEAD,fontSize:24,bold:true,color:C.goldSoft,align:"center"});addText(s,"合书以后，只讲这三层",{x:8.82,y:5.65,w:3.78,h:.38,fontSize:20,bold:true,color:C.warm,align:"center"});addText(s,"故事轨道｜第三格",{x:.82,y:6.62,w:2.12,h:.3,fontSize:18,bold:true,color:C.leafSoft});line(s,p,3.2,6.86,8.73,C.leaf,2,0);addNotes(s,page);}

function validateObjects(p,n){const e=[];if(p._slides.length!==n)e.push(`slides ${p._slides.length}/${n}`);p._slides.forEach((s,i)=>{if(!s._slideObjects.some(x=>x._type==="notes"))e.push(`slide ${i+1} missing notes`);s._slideObjects.forEach((x,j)=>{const o=x.options||{};if([o.x,o.y,o.w,o.h].every(v=>typeof v==="number")&&(o.x<-.01||o.y<-.01||o.x+o.w>W+.01||o.y+o.h>H+.01))e.push(`slide ${i+1} object ${j+1} out of bounds`);});});if(e.length)throw new Error(e.join("\n"));}
async function repairNotesMaster(f){const z=await JSZip.loadAsync(fs.readFileSync(f));const e=z.file("ppt/presentation.xml");let x=await e.async("string");const m=x.match(/<p:notesMasterIdLst>[\s\S]*?<\/p:notesMasterIdLst>/);if(m){x=x.replace(m[0],"");x=x.replace(/(<p:sldMasterIdLst>[\s\S]*?<\/p:sldMasterIdLst>)/,`$1${m[0]}`);}z.file("ppt/presentation.xml",x);fs.writeFileSync(f,await z.generateAsync({type:"nodebuffer",compression:"DEFLATE"}));}
async function main(){const v=validate(source);if(!v.ok)throw new Error(JSON.stringify(v.errors));const snap=JSON.parse(fs.readFileSync(SNAPSHOT,"utf8"));if(snap.source_sha256!==sha256(path.join(PROJECT_ROOT,"scripts","meng_v62","content","chapter_3.js")))throw new Error("stale snapshot");const map=new Map(snap.pages.map(x=>[x.page_id,x]));const plan=[["C301",renderC301,"完整章声与换声初稿"],["C302",renderC302,"沃若感官与开放假设"],["C303",renderC303,"呼告转移与蒙句听辨"],["C305",renderC305,"脱身处境对照与边界"],["C306",renderC306,"撤答整章回望"]];const pages=plan.map(([id,r,d],i)=>({...map.get(id),renderer:r,duty:d,physicalIndex:i+1}));const pres=presentation();pages.forEach(x=>x.renderer(pres.addSlide(),pres,x));validateObjects(pres,pages.length);fs.mkdirSync(OUT,{recursive:true});await pres.writeFile({fileName:PPTX,compression:true});await repairNotesMaster(PPTX);const manifest={schema_version:"1.1",module_id:source.module_id,version:source.version,artifact:path.relative(PROJECT_ROOT,PPTX).split(path.sep).join("/"),sha256:sha256(PPTX),source_snapshot_sha256:sha256(SNAPSHOT),physical_slides:pages.map(x=>({physical_index:x.physicalIndex,page_id:x.page_id,primary_visual_duty:x.duty,unique_function:x.unique_function})),illustration_policy:"no_character_illustration_until_all_lesson_functions_are_frozen",claim_boundary:"chapter3_candidate_not_classroom_observed"};fs.writeFileSync(MANIFEST,`${JSON.stringify(manifest,null,2)}\n`);process.stdout.write(`V64_CHAPTER3_PPTX_OK slides=${pages.length} pptx=${PPTX}\n`);}
main().catch(e=>{process.stderr.write(`${e.stack||e}\n`);process.exit(1);});
