"use strict";

const methods = [
  {
    method_id: "M_MEMORY_LADDER",
    name: "记忆提示阶梯",
    reading_difficulty: "学生的文学记忆广度不同，直接报篇名会把教师提示变成公共答案，完全不提示又会让空白者失去入口",
    student_action: "每人先静默检索；仍空白者依次使用本班篇目目录、只写篇名提示条或先听后补，并自行写出朴素主题",
    artifact: "标明所用恢复路径且至少一项由本人写成的作品清单",
    feedback_revision: "教师只提供检索线索，不提供主题；学生听到同伴后仍须用自己的话补写",
    return_to_text: "个人清单进入编号轮说并保留作者来源",
    participation_denominator: "全班每人",
    answer_visibility_state: "主题答案始终隐藏；提示只到篇名",
    recovery_branches: ["目录", "篇名提示条", "先听后补"],
  },
  {
    method_id: "M_NUMBERED_ROUND",
    name: "静默准备后的编号轮说",
    reading_difficulty: "自愿发言会让快想者或外向者长期占据公共声音，其他学生只有旁听",
    student_action: "先独立留下材料，再按1—4号依次发言；听者同步勾记，执笔人发言时由下一位代记",
    artifact: "能追溯四名组员来源的小组作品谱，以及带组号、卡号、原提议者号和签认的贡献卡",
    feedback_revision: "超时者被有界收束，空白者先听一人再自行补写；不允许同伴代答",
    return_to_text: "全员材料共同形成公开贡献卡；原提议者保留作者权并签认卡面表述",
    participation_denominator: "每个四人组4/4",
    speaker_rotation: "编号固定一轮，执笔职责换手",
  },
  {
    method_id: "M_LIVE_CARD_CLUSTER",
    name: "现场卡墙结网",
    reading_difficulty: "教师预制分类会把广泛回忆重新压成教师答案，只有一人移动又不能证明主题谱由学生生成",
    student_action: "每人先连接两张卡并临时命名；至少三名不同学生移动、命名、引用卡片文字；全班执行保留、改名或移回",
    artifact: "带卡号、学生命名和修订痕迹的主题谱",
    feedback_revision: "听众只能指出卡片依据、名字说满或证据不足；原提议者亲自保留、改名或移回",
    return_to_text: "揭题时调用现场主题谱，全文圆桌再次读取并修订",
    participation_denominator: "全班每人先写；至少三名不同公开提议者；全班每人反馈",
    answer_visibility_state: "教师、PPT、学习单和物料均无预制类别",
    material_logistics: "贡献卡编号、粗头笔、磁贴墙、可读照片备份",
  },
  {
    method_id: "M_ACTOR_MARK",
    name: "人物动作着色",
    reading_difficulty: "四言诗句短促，学生容易逐词翻译，却没有看清一章中两个人怎样轮流行动",
    student_action: "每人先在原句中圈男子动作、划女子动作，再与同桌核对行动主体",
    artifact: "第一章原句上的人物动作标记",
    feedback_revision: "同桌逐项追问‘谁在做’，标错者换笔修订",
    return_to_text: "带着修订后的动作标记完整重读第一章",
  },
  {
    method_id: "M_GLOSS_REVISE",
    name: "先译后校",
    reading_difficulty: "关键词阻挡句意，但直接给现成译文会让学生跳过自己的语言加工",
    student_action: "每人先把原句说成一句自然现代话，再使用定点释义校准",
    artifact: "一条保留修改痕迹的现代话复述",
    feedback_revision: "同桌只核对人物、动作和对象，作者换笔修改一处不准确表达",
    return_to_text: "修改后再读原句，说明现代话中的哪一部分由哪个原词支撑",
  },
  {
    method_id: "M_INTENT_CONTRAST",
    name: "动作与来意转折对读",
    reading_difficulty: "学生容易把‘贸丝/谋’一口气贴成欺骗或品格标签，忽略诗句当下只明写动作与女子随后说明的议婚来意",
    student_action: "每人分别写下诗句先写的贸丝动作和女子随后说明的议婚来意，并圈出否定转折",
    artifact: "一组‘先写动作—随后说明来意—否定转折’对读记录",
    feedback_revision: "听者检查结论是否超出‘匪、贸、谋’能够证明的范围",
    return_to_text: "用‘不是……而是……’重读并复述两句的推进",
  },
  {
    method_id: "M_ROUTE_TRACE",
    name: "空间行迹",
    reading_difficulty: "‘涉淇—顿丘’容易被当成两个地名，女子远送的行动长度没有进入理解",
    student_action: "每人用一条线标出从送行、渡淇到顿丘的移动，并补全行动主体",
    artifact: "一条带人物和终点的送行路线",
    feedback_revision: "同桌找路线中的断点，作者依据‘送、涉、至’补齐",
    return_to_text: "把三个动作连成一句现代话，再回读原句",
  },
  {
    method_id: "M_CLAUSE_SORT",
    name: "两种读法原词裁断",
    reading_difficulty: "学生容易把女子说明媒妁条件读成拒婚，或把后来的悲剧倒灌为她故意拖延",
    student_action: "每人先在‘拒绝婚事／说明此刻条件’两种读法中选择，再抄下托住判断的原词",
    artifact: "一项带原词依据、经校准后可修订的句意判断",
    feedback_revision: "同桌只问选择由哪个词托住；作者在教师定点释义后保留或换笔改写",
    return_to_text: "带着修订后的解释语气重读‘匪我愆期，子无良媒’",
  },
  {
    method_id: "M_TONE_READING",
    name: "语气选择与重读",
    reading_difficulty: "‘将子无怒’既有请求又有安抚，单一情绪标签会压扁声音层次",
    student_action: "每人先选一处重音和一处停顿，读出请求、安抚与约期的并存",
    artifact: "一条有原词依据的朗读标记",
    feedback_revision: "听者说出自己实际听见的语气及对应原词，读者据此改读",
    return_to_text: "保留修订标记，完整重读‘将子无怒，秋以为期’",
  },
  {
    method_id: "M_RETRIEVAL_CHAIN",
    name: "遮答行动链",
    reading_difficulty: "逐句都懂以后，学生仍可能离开屏幕就无法连续讲清事件",
    student_action: "合上书，独立写出五个连续动作，再与同桌互相查漏",
    artifact: "一条由个人记忆重建并换笔修订的五步行动链",
    feedback_revision: "同桌只指出断点、不报完整答案；作者翻书定位后换笔补回",
    return_to_text: "依据修订后的行动链重新通读第一章，核对顺序",
  },
  {
    method_id: "M_EVIDENCE_BOUNDARY",
    name: "诗中所写—初读所感—暂且留白",
    reading_difficulty: "初见印象容易被后来结局倒灌，成为无证据的宿命判断或对受伤者的归责",
    student_action: "每人分别写‘诗里写着、初读时我觉得、现在还说不准’，并给前两栏补原词",
    artifact: "三栏初见札记",
    feedback_revision: "听者查找说满之处，作者将判断保留、说轻一点或移入‘现在还说不准’",
    return_to_text: "给每条保留判断补一处第一章原词，全文后重新打开档案",
  },
  {
    method_id: "M_CHAPTER_RETELL",
    name: "整章重读与三十秒旁白",
    reading_difficulty: "字词知识与局部活动可能仍是碎片，学生没有形成可连续表达的本章理解",
    student_action: "每人完整重读第一章，再用三十秒讲清男子怎样来、女子怎样回应、婚期怎样定",
    artifact: "一段可由原诗重建的第一章口头旁白和一句章意",
    feedback_revision: "听者按三项标准指出遗漏，讲述者回诗定位后补说一次",
    return_to_text: "以修订后的旁白带回整章朗读，并接入第二章等待场景",
  },
  {
    method_id: "M_ACTION_PULSE_READ",
    name: "动作脉冲初读",
    reading_difficulty: "第二章动作密集且情绪转折快，学生初读时容易只看见哭与笑，忽略动作顺序怎样托住变化",
    student_action: "每人完整朗读一章，遇到人物动作轻点一次，并把最确定的三个动作依次写下",
    artifact: "一条只含三个初读动作的脉冲记录",
    feedback_revision: "同桌只核对动作在诗中的先后，不补写情绪标签；作者回诗调序",
    return_to_text: "按修订后的动作顺序再读全章，进入第一处空间动作",
  },
  {
    method_id: "M_SIGHTLINE_TRACE",
    name: "视线线条",
    reading_difficulty: "‘乘—望—复关’容易被逐词译完，却没有形成登高、远望和望向何处的空间关系",
    student_action: "每人先定位女子已立于垝垣上，再画一条由此指向复关的视线，并标出乘、望和望向对象",
    artifact: "一条从垝垣顶端人物点指向复关的视线线条",
    feedback_revision: "同桌先检查人物是否已在垝垣上，再检查线条是视线还是行走路线；混淆者依据‘乘’‘望’改画",
    return_to_text: "沿视线方向一口气重读原句，保持‘乘—望’动作连续",
  },
  {
    method_id: "M_CONTRAST_COUPLET",
    name: "对照句并读",
    reading_difficulty: "把‘不见’和‘既见’拆开逐句讲，会失去视线变化、动作变化和声音变化的正面对照",
    student_action: "每人将两句并排，对齐不见/既见、泣涕/笑言，再把两句分别说成自然话",
    artifact: "一组两行对齐并保留修订的对照句",
    feedback_revision: "同伴遮住情绪词，只凭对齐的原词检查转折；作者换笔补回漏项",
    return_to_text: "带着对照重新连读两句，让‘不见—既见’成为声音转轴",
  },
  {
    method_id: "M_READING_SCORE_DESIGN",
    name: "双速度朗读谱",
    reading_difficulty: "学生知道女子先哭后笑，却未必能把动作顺序转成可听见的速度、停顿和重音",
    student_action: "每人先为两句设计快慢、停顿和重音，并为一处选择写出原词依据",
    artifact: "一份个人双速度朗读谱",
    feedback_revision: "教师只核对标记能否由‘不见/既见、涟涟、载’支撑，不先给标准读法",
    return_to_text: "依据个人朗读谱完整读两句，准备交给听者盲听",
  },
  {
    method_id: "M_LISTENER_READING_TEST",
    name: "闭眼听辨与改读",
    reading_difficulty: "朗读标记可能只停在纸上，读者自己以为读出了变化，听者却实际听不见",
    student_action: "读者按朗读谱读，听者闭眼只写听见的转轴和对应原词；读者根据回执改读一次",
    artifact: "听者回执和读者修订后的第二遍朗读",
    feedback_revision: "听者不评价好坏，只指出哪处变化听得见/听不见；读者据此改变一处速度、停顿或重音",
    return_to_text: "以听者能辨认的第二遍朗读重新连接两句",
  },
  {
    method_id: "M_MICRO_CULTURE_BOUNDARY",
    name: "微型文化支架与边界",
    reading_difficulty: "卜、筮、体、咎言属于先秦文化语境，学生既可能无法口译，也可能把无咎误当成长期幸福保证",
    student_action: "每人把四个词放回原句口译，再区分此次占问结果与后来关系结果",
    artifact: "一条卜筮小注和一条不能说满的边界句",
    feedback_revision: "同伴查找‘一定、保证、证明’等越界词，作者改为此次占问没有显示不祥",
    return_to_text: "带着文化小注重读原句，确认它在叙事中只推进婚前程序",
  },
  {
    method_id: "M_PARALLEL_ACTIONS",
    name: "对称句式拆行动",
    reading_difficulty: "‘以尔/以我’的对称容易被译成一句泛泛的‘成婚’，双方不同动作和女子携财物迁嫁的事实被压扁",
    student_action: "每人沿‘以尔—以我’分成两栏，分别补出谁带来什么、谁带着什么迁往何处",
    artifact: "一组对称行动记录",
    feedback_revision: "听者检查两栏主体、物件和动作是否错位，作者回到原词换笔修订",
    return_to_text: "按两栏动作一人一句对读，再合为完整原句",
  },
  {
    method_id: "M_SCRAMBLED_ACTION_VOICE",
    name: "章首三步连接七个关键节点",
    reading_difficulty: "章首初读动作如果没有后用会成为一次性练习；逐句完成后仍需检验学生能否把最初三步扩成完整顺序并定位转折",
    student_action: "写回章首三个动作，七词中找得到的圈出、没有出现的合理动作保留；合书给七词复位编号，再在自己的排序中圈出声音转折并连住前后节点",
    artifact: "章首三步与七个关键节点的对应记录、一条经换笔修订的七词顺序和学生自行定位的转折线",
    feedback_revision: "同桌只指出顺序断点或所连两项是否相邻，不报完整顺序和正确转折词；作者翻诗定位后修订",
    return_to_text: "依据修订后的七步和转折线完整重读第二章",
  },
  {
    method_id: "M_STORY_RAIL_RECALL",
    name: "章意接续轨道",
    reading_difficulty: "逐章活动产物分散在学习单中，学生跨章后容易记得操作却说不清人物生活已经走到哪里",
    student_action: "每人从前两章一句章意中各提取一句自然话，同桌合并后写入同一条故事轨道，并为新章留出空格",
    artifact: "一条持续增长且保留学生自然话的六章故事轨道",
    feedback_revision: "同桌只检查人物、动作和事件转折是否齐全，作者回到章末章意改写；不把活动名称写进轨道",
    return_to_text: "新章结束时把本章自然话接入同一轨道，下一章开头继续调用",
  },
  {
    method_id: "M_CAMERA_SHIFT_READ",
    name: "镜头落点初读",
    reading_difficulty: "第三章突然停止婚事叙述，转向桑叶、斑鸠和劝诫；学生若只逐词翻译，会看不见叙事方式的突然变化",
    student_action: "每人完整朗读第三章，镜头或呼告对象改变时轻停半拍，读后只写三个最确定的画面或对象",
    artifact: "一条由初读留下的三处镜头落点记录",
    feedback_revision: "同桌只核对所写对象是否来自本章，不替对方解释比兴或主题；作者回诗换笔修订",
    return_to_text: "章末用三处落点重建第三章声音怎样由物转向人",
  },
  {
    method_id: "M_SENSORY_HYPOTHESIS",
    name: "感官观察与意象假设",
    reading_difficulty: "学生容易先背‘桑叶比喻青春’的标准答案，跳过沃若的色泽、质地和生命状态，也把开放意象压成一对一密码",
    student_action: "每人先依据‘沃若’写两个感官词，再提出两种可能联想并标明只是待后文筛选的假设",
    artifact: "一张含感官词、两项解释假设和问号标记的桑叶假设卡",
    feedback_revision: "同伴只追问联想从哪一感官词产生，不替作者选唯一答案；无原词依据者换笔改弱",
    return_to_text: "第四章‘黄而陨’出现时重新打开假设卡，用前后位置和状态对照筛选",
  },
  {
    method_id: "M_ECHO_ADDRESS_READING",
    name: "呼告回声对读",
    reading_difficulty: "于嗟、无、兮在两句中反复，若分开讲词义，学生听不见诗怎样由劝鸠突然转为劝女",
    student_action: "两人先分别口译鸠句和女句，再按相同节拍对读；听者圈出重复框架并框住改变的对象与劝告",
    artifact: "一组标出重复呼告和变化对象的双句回声记录",
    feedback_revision: "听者只指出哪一处重复或变化没有落在原词上，读者换笔补词后再对读",
    return_to_text: "带着呼告回声连读桑叶、鸠和女子三句，听见由物及人的推进",
  },
  {
    method_id: "M_EXIT_CONDITION_CONTRAST",
    name: "同词异势对读",
    reading_difficulty: "学生可能把‘士可说、女不可说’解释成女性天生更脆弱，或把女子投入写成男子伤害她的原因",
    student_action: "每人圈出两句完全相同的‘耽、说’，框出真正改变判断的‘士/女、犹可/不可’，再写一句只陈述脱身处境差异的自然话",
    artifact: "一组同词、异词标记和一条不越界的处境对照句",
    feedback_revision: "同伴圈出‘天生、活该、导致他’等越界归因，作者删去并把原因标为后文待证",
    return_to_text: "下一章读取婚后事实，检验何种生活与关系结构使不平等退出成为现实",
  },
  {
    method_id: "M_DELETION_COMPARISON",
    name: "删句比较发现比兴",
    reading_difficulty: "直接给出‘比兴’定义会把手法变成术语清单，学生不知道桑叶和斑鸠为何不能无损删除",
    student_action: "小组先后朗读保留桑叶斑鸠的原段与直接从劝女开始的删改段，写下原段多带来的一个画面、一层声音或一段情感铺垫",
    artifact: "一条由删句比较生成的‘原段不可替代之处’解释",
    feedback_revision: "听者要求解释落回沃若、于嗟、鸠、女等原词；只报术语者须补可感效果",
    return_to_text: "教师在体验后命名由物起兴、由物及人的比兴，并让学生带着解释重读原段",
  },
  {
    method_id: "M_VOICE_STAIRCASE_RETRIEVAL",
    name: "第三章四级声音阶梯",
    reading_difficulty: "逐句学习后，学生可能只留下词义和活动步骤，不能恢复第三章由景入诫、由物及人、再到处境对照的声音推进",
    student_action: "合书给五张乱序短签编号，写回于嗟反复和可/不可对照的位置，再用自然话说明每一级新增什么",
    artifact: "一条把五句原诗压缩为四级推进、由个人记忆复位并换笔修订的声音阶梯",
    feedback_revision: "同桌只指出断层或缺少原词的位置，不报完整顺序；作者翻诗定位后修订",
    return_to_text: "依据声音阶梯完整重读并完成第三章三十秒旁白",
  },
  {
    method_id: "M_KNOWLEDGE_SHELF",
    name: "字词—声音—边界收纳",
    reading_difficulty: "体验活动结束后，学生需要把分散的字词、语言形式和解释边界收束成可复习知识，但总结若过早出现会覆盖生成",
    student_action: "在完成章末旁白之后，用自己的记录逐项核对字词、声音推进和解释边界，对一处仍不稳的知识作星标",
    artifact: "一份经过生成后才出现、带个人星标的第三章知识收纳",
    feedback_revision: "教师只处理学生星标项；学生用原句补证，不重新抄写全部答案",
    return_to_text: "第四章遇到黄而陨、婚后事实和责任判断时分别调用桑叶假设、处境问题和字词知识",
  },
];

const payload = { schema_version: "1.0", methods };

if (require.main === module) process.stdout.write(`${JSON.stringify(payload)}\n`);

module.exports = payload;
